// Descriptions follow the existing Canva-aligned grammar memberships.
// No chapter title, grammar point, lesson order or membership is changed.
const data = [
  ['Describing Things and Activities','Menjelaskan benda dengan klausa sederhana, menyebut kegiatan, dan menghindari pengulangan nama benda.','Memilih buku atau barang serta menceritakan hobi kepada teman.',['Menerangkan benda memakai verba bentuk biasa sebelum kata benda.','Menyebut kegiatan dengan の／こと sesuai fungsi kalimat.','Menggantikan kata benda yang sudah diketahui dengan kata sifat + の.']],
  ['Explanations, Opinions and Quotations','Menyampaikan alasan latar, pendapat, ucapan orang lain, nama, dan pertanyaan kepada diri sendiri.','Menjelaskan keadaan kepada teman, lalu menyampaikan pesan dan pendapat.',['Menggunakan んです untuk menjelaskan latar keadaan.','Menyatakan pendapat dan mengutip informasi dengan と.','Memperkenalkan nama dengan という dan mengungkapkan keraguan dengan かな.']],
  ['Time, Sequence and Simultaneous Activities','Menentukan waktu kegiatan, urutan, durasi, tenggat, dan kegiatan yang berlangsung bersamaan.','Menyusun kegiatan harian dan menjelaskan pekerjaan sebelum batas waktu.',['Membedakan 前に／後で serta 間／間に.','Membedakan kegiatan sampai waktu tertentu dan penyelesaian paling lambat dengan まで／までに.','Menghubungkan kegiatan dengan たり、ながら、ないで.']],
  ['Ability and Perception','Menyampaikan kemampuan, hal yang dapat dilakukan, serta bunyi, penglihatan, bau, dan rasa yang tertangkap.','Menjelaskan kemampuan pribadi dan keadaan di sekitar tempat tinggal.',['Menyatakan kemampuan dengan bentuk potensial dan ことができる.','Membedakan kemampuan melihat/mendengar dari hal yang tertangkap indra.','Menyatakan adanya suara, bau, dan rasa dengan がする.']],
  ['Intentions, Decisions and Habits','Menyampaikan niat, keputusan, kebiasaan, perubahan kemampuan, dan usaha yang dilakukan secara rutin.','Membuat rencana belajar dan menjelaskan kebiasaan baru.',['Menyampaikan niat memakai bentuk volisional + と思う.','Membedakan keputusan pribadi ことにする dan keputusan/keadaan ことになる.','Menjelaskan kebiasaan dan perubahan dengan ことにしている／ようになる／ようにする.']],
  ['Trying, Completing and Responding to Results','Mencoba tindakan, menyampaikan penyelesaian atau penyesalan, dan menanggapi hasil dengan lega atau permintaan maaf.','Mencoba kegiatan baru dan menjelaskan hasilnya kepada teman.',['Menyatakan percobaan dengan てみる.','Membedakan penyelesaian dan penyesalan pada てしまう.','Mengungkapkan rasa lega dan meminta maaf atas tindakan atau tidak dilakukannya tindakan.']],
  ['Verb Pairs, States and Preparation','Membedakan pelaku tindakan, perubahan keadaan, hasil yang bertahan, serta persiapan yang disengaja.','Menyiapkan ruangan dan menjelaskan keadaan pintu, jendela, dan barang.',['Memilih を／が sesuai verba transitif dan intransitif.','Membedakan keadaan ている dengan hasil persiapan てある.','Menyampaikan tindakan persiapan dengan ておく.']],
  ['Direction, Change and Stages of Activities','Menyampaikan arah gerakan, perkembangan, awal dan akhir kegiatan, serta tahap kegiatan yang sedang berlangsung.','Memberi kabar perkembangan belajar dan status pekerjaan.',['Menggunakan ていく／てくる sesuai arah dan sudut pandang waktu.','Menjelaskan awal, kelanjutan, dan akhir tindakan.','Membedakan ところ、ばかり、もう、まだ sesuai tahap aktivitas.']],
  ['Methods, Ease and Changes in Qualities','Menjelaskan cara melakukan sesuatu, kemudahan, kesulitan, kelebihan, dan perubahan sifat.','Menjelaskan cara memakai alat dan memilih barang yang nyaman digunakan.',['Menjelaskan cara dengan 方 dan menilai kemudahan dengan やすい／にくい.','Menyatakan kadar berlebihan memakai すぎる.','Mengubah sifat menjadi keterangan, perubahan yang disengaja, dan nomina dengan く／に、くする／にする、さ.']],
  ['Reasons, Contrasts and Concessions','Menyampaikan sebab, beberapa alasan, kontras, hasil yang tidak diharapkan, serta keadaan yang tetap berlaku.','Menjelaskan pilihan tempat tinggal dan perubahan rencana.',['Menghubungkan alasan dengan ので、し、て／なくて.','Membedakan kontras biasa けど dari harapan yang tidak terpenuhi pada のに.','Menyatakan hasil yang tetap berlaku dengan ても／でも.']],
  ['Inference and Reported Information','Membedakan penilaian dari tampilan, kabar orang lain, kemungkinan, dugaan, dan kesimpulan beralasan.','Membicarakan cuaca, jadwal, dan kabar yang belum dipastikan.',['Membedakan そうだ berdasarkan tampilan dan そうだ sebagai kabar.','Memilih らしい、かもしれない、でしょう sesuai dasar dan kekuatan dugaan.','Menjelaskan perkiraan beralasan dengan はずだ／はずがない.']],
  ['Similarity, Feelings and Wants','Menyatakan kemiripan, tampilan perasaan, serta keinginan orang lain dari tanda yang terlihat.','Menceritakan keadaan keluarga dan kesan terhadap benda atau suasana.',['Memakai ようだ／みたいだ untuk kemiripan atau kesimpulan dari tanda.','Menerangkan benda dan tindakan dengan そうな／そうに.','Menyampaikan perasaan dan keinginan orang lain dengan がる、たがる、欲しがる.']],
  ['Conditions with To and Tara','Membicarakan hasil yang teratur, kondisi setelah suatu kejadian, saran, dan harapan.','Memberi petunjuk perjalanan dan saran saat teman menghadapi masalah.',['Memilih と untuk hasil teratur dan たら untuk kondisi yang lebih luas.','Memberi saran dengan たらどうですか.','Menyatakan harapan dengan といい.']],
  ['Conditions with Ba and Nara','Menyampaikan syarat, menanggapi topik yang disampaikan lawan bicara, dan menyesali tindakan lampau.','Menanggapi rencana perjalanan serta menjelaskan pilihan yang disesali.',['Membentuk syarat ば dan memperhatikan hubungan dengan klausa hasil.','Menggunakan なら untuk saran atau informasi berdasarkan topik lawan bicara.','Menyatakan penyesalan dengan ばよかった／なければよかった.']],
  ['Purposes, Uses and Indirect Instructions','Menyampaikan tujuan perjalanan dan tindakan, kegunaan benda, serta instruksi yang disampaikan kembali.','Menjelaskan tujuan membeli alat dan menyampaikan pesan guru.',['Menyampaikan tujuan perjalanan memakai に行く／来る／帰る.','Membedakan tujuan tindakan ために dan hasil yang diupayakan ように.','Menjelaskan kegunaan dengan のに dan meneruskan instruksi dengan ように言う.']],
  ['Advice, Obligations and Firm Instructions','Memberi saran, menyatakan kewajiban dan kebutuhan, serta mengenali instruksi tegas sesuai hubungan pembicara.','Membicarakan persiapan kegiatan dan memahami larangan pada tanda atau pengumuman.',['Memberi saran positif dan negatif dengan ほうがいい.','Membedakan kewajiban dari perlu/tidak perlunya tindakan.','Mengenali なさい、bentuk perintah、dan larangan るな beserta batas pemakaiannya.']],
  ['Giving and Receiving Things','Menceritakan perpindahan benda dengan sudut pandang pemberi, penerima, atau pihak pembicara.','Menceritakan pemberian hadiah di keluarga dan antarteman.',['Memakai あげる dari sudut pandang pemberi.','Memakai もらう dari sudut pandang penerima.','Memakai くれる untuk pemberian kepada pembicara atau kelompoknya.']],
  ['Help, Requests and Wishes','Menceritakan bantuan, meminta tindakan dengan sopan, menyampaikan harapan, dan berterima kasih.','Meminta bantuan teman dan menghargai bantuan yang diterima.',['Membedakan arah manfaat pada てあげる、てくれる、てもらう.','Meminta bantuan dengan てもらえませんか／てくれませんか.','Menyampaikan harapan tindakan dan berterima kasih atas bantuan.']],
  ['Embedded Questions and Quantity Limits','Menyampaikan informasi yang belum diketahui, membatasi jumlah, dan menambahkan unsur dalam penjelasan.','Bertanya tentang layanan dan menjelaskan jumlah barang atau kebiasaan.',['Menanamkan pertanyaan dengan か／かどうか.','Membedakan だけ、しか、ばかり berdasarkan makna dan bentuk kalimat.','Menggunakan だけで、だけでなく、dan penekanan jumlah dengan も／は.']],
  ['Comparison, Limits and Conditions','Membandingkan tingkat, menyampaikan perkiraan dan frekuensi, serta menjelaskan batas, keadaan, dan petunjuk.','Membaca aturan jumlah dan menjelaskan cara mengikuti petunjuk.',['Membandingkan dengan ほど dan membedakan くらい／ごろ.','Menyatakan frekuensi serta batas yang termasuk atau tidak termasuk.','Menjelaskan keadaan dengan 場合、まま、dan とおりに.']],
  ['Passive Sentences','Menceritakan tindakan dari sudut pandang penerima atau pihak terdampak, serta informasi umum tentang benda.','Menceritakan kejadian pribadi dan menjelaskan asal sebuah benda atau karya.',['Membentuk verba pasif dan membedakannya dari bentuk potensial yang serupa.','Menyampaikan pasif langsung serta dampak pada kepemilikan atau keadaan.','Menyampaikan informasi umum dengan pasif dan pelaku によって.']],
  ['Causative and Causative Passive','Menyatakan seseorang menyuruh atau mengizinkan tindakan serta pengalaman dipaksa melakukan sesuatu.','Menceritakan instruksi di sekolah dan permintaan izin melakukan tindakan.',['Membentuk kausatif serta memilih partikel pelaku sesuai verba.','Menggabungkan kausatif dengan permintaan dan pemberian izin.','Membentuk kausatif-pasif dan mengenali bentuk pendek yang sesuai.']],
  ['Respectful Language: Sonkeigo','Menyampaikan tindakan orang yang dihormati dengan pola umum dan verba hormat khusus.','Membicarakan kegiatan guru atau tamu dan memberi arahan dengan hormat.',['Membentuk sonkeigo dengan お／ご〜になる dan bentuk pasif hormat.','Memilih verba hormat khusus sesuai tindakan orang yang dihormati.','Memakai konjugasi sopan khusus dan お／ご〜ください.']],
  ['Humble Language and Formal Requests','Menyampaikan tindakan diri sendiri dengan merendah, memberi layanan formal, meminta bantuan, dan berterima kasih.','Menerima tamu, menjelaskan tindakan sendiri, dan meminta bantuan secara formal.',['Memilih お／ご〜する、いたす dan verba merendah sesuai pihak yang dihormati.','Memakai ございます／でございます pada konteks formal.','Membedakan pemberian/penerimaan hormat dan merendah serta menyusun permintaan dan ucapan terima kasih.']],
];
export const chapters=data.map(([title_en,description,scenario,cando_statements],index)=>({chapter:index+1,title_en,description,scenario,cando_statements}));
