-- Generated by scripts/build-n5-grammar-support.mjs from the reviewed corpus.
-- This phase changes examples, contextual drills and task instructions only.
-- Core rows, lesson/task memberships, counts, notes and all dialogue data stay intact.
-- Exact captured support is checked before replacement; uncaptured configs must be NULL.
ALTER TABLE module_grammar ADD COLUMN IF NOT EXISTS practice_config JSONB;
CREATE TABLE IF NOT EXISTS n5_grammar_support_backup_184 (
  grammar_id UUID PRIMARY KEY,
  before_grammar JSONB NOT NULL,
  before_examples JSONB NOT NULL,
  after_grammar JSONB,
  after_examples JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS n5_grammar_task_support_backup_184 (
  lesson_id UUID NOT NULL,
  grammar_id UUID NOT NULL,
  before_item JSONB NOT NULL,
  after_item JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (lesson_id,grammar_id)
);
DO $support$
DECLARE
  plan JSONB := $content$__CONTENT__$content$::jsonb;
  chapter JSONB; item JSONB; task_item JSONB; replacement JSONB;
  grammar_row module_grammar%ROWTYPE;
  task_row lesson_grammar_task_items%ROWTYPE;
  actual_core JSONB; actual_examples JSONB;
  target_count INT; task_count INT; saved_count INT; saved_tasks INT;
  target_id UUID;
BEGIN
  -- Temporary manifest deduplicates source rows also used directly by a task.
  CREATE TEMP TABLE grammar_targets_184 (id UUID PRIMARY KEY, data JSONB NOT NULL) ON COMMIT DROP;
  CREATE TEMP TABLE task_targets_184 (lesson_id UUID,grammar_id UUID,data JSONB NOT NULL,PRIMARY KEY(lesson_id,grammar_id)) ON COMMIT DROP;
  FOR chapter IN SELECT value FROM jsonb_array_elements(plan->'chapters') LOOP
    FOR item IN SELECT value FROM jsonb_array_elements(chapter->'items') LOOP
      INSERT INTO grammar_targets_184 VALUES ((item->>'id')::uuid,item);
    END LOOP;
    FOR task_item IN SELECT value FROM jsonb_array_elements(chapter->'taskItems') LOOP
      INSERT INTO task_targets_184 VALUES ((task_item->>'lessonId')::uuid,(task_item->>'grammarId')::uuid,task_item);
      INSERT INTO grammar_targets_184 VALUES ((task_item->>'grammarId')::uuid,task_item) ON CONFLICT (id) DO NOTHING;
    END LOOP;
  END LOOP;
  SELECT count(*) INTO target_count FROM grammar_targets_184;
  SELECT count(*) INTO task_count FROM task_targets_184;
  SELECT count(*) INTO saved_count FROM n5_grammar_support_backup_184 b JOIN grammar_targets_184 t ON t.id=b.grammar_id;
  SELECT count(*) INTO saved_tasks FROM n5_grammar_task_support_backup_184 b JOIN task_targets_184 t USING(lesson_id,grammar_id);
  -- A successful replay must leave subsequent teacher edits alone.
  IF saved_count=target_count AND saved_tasks=task_count THEN RETURN; END IF;
  IF saved_count<>0 OR saved_tasks<>0 THEN RAISE EXCEPTION '184 partial backup ledger; inspect before applying'; END IF;
  IF (SELECT count(*) FROM courses WHERE id=(plan->>'courseId')::uuid AND slug=plan->>'courseSlug')<>1 THEN
    RAISE EXCEPTION '184 course identity changed';
  END IF;
  FOR chapter IN SELECT value FROM jsonb_array_elements(plan->'chapters') LOOP
    IF (SELECT count(*) FROM modules WHERE id=(chapter->>'moduleId')::uuid AND course_id=(plan->>'courseId')::uuid AND slug=chapter->>'moduleSlug')<>1 THEN
      RAISE EXCEPTION '184 module identity changed: %',chapter->>'moduleSlug';
    END IF;
    FOR item IN SELECT value FROM jsonb_array_elements(chapter->'items') LOOP
      IF (SELECT count(*) FROM lessons WHERE id=(item->>'lessonId')::uuid AND module_id=(chapter->>'moduleId')::uuid AND slug=item->>'lessonSlug')<>1 THEN
        RAISE EXCEPTION '184 source lesson identity changed: %',item->>'lessonSlug';
      END IF;
    END LOOP;
    FOR task_item IN SELECT value FROM jsonb_array_elements(chapter->'taskItems') LOOP
      IF (SELECT count(*) FROM lessons WHERE id=(task_item->>'lessonId')::uuid AND module_id=(chapter->>'moduleId')::uuid AND slug=task_item->>'lessonSlug')<>1 THEN
        RAISE EXCEPTION '184 task lesson identity changed: %',task_item->>'lessonSlug';
      END IF;
    END LOOP;
  END LOOP;
  -- Lock all affected rows before validation, so concurrent edits cannot slip
  -- between the before-support comparison and the write.
  LOCK TABLE grammar_examples,lesson_grammar_task_items IN SHARE ROW EXCLUSIVE MODE;
  PERFORM 1 FROM module_grammar WHERE id IN(SELECT id FROM grammar_targets_184) FOR UPDATE;
  PERFORM 1 FROM lesson_grammar_task_items gi WHERE (gi.lesson_id,gi.grammar_id) IN(SELECT lesson_id,grammar_id FROM task_targets_184) FOR UPDATE;
  FOR target_id,item IN SELECT id,data FROM grammar_targets_184 LOOP
    SELECT * INTO grammar_row FROM module_grammar WHERE id=target_id;
    IF NOT FOUND THEN RAISE EXCEPTION '184 missing grammar %',target_id; END IF;
    actual_core=jsonb_build_object('id',grammar_row.id,'module_id',grammar_row.module_id,'lesson_id',grammar_row.lesson_id,
      'pattern',grammar_row.pattern,'meaning',grammar_row.meaning,'sort_order',grammar_row.sort_order);
    IF actual_core IS DISTINCT FROM item->'expectedCore' THEN RAISE EXCEPTION '184 immutable grammar changed: %',target_id; END IF;
    SELECT COALESCE(jsonb_agg(jsonb_build_object('japanese',japanese,'highlight',highlight,'indonesian',indonesian,'sort_order',sort_order) ORDER BY sort_order,japanese),'[]'::jsonb)
      INTO actual_examples FROM grammar_examples WHERE grammar_id=target_id;
    IF grammar_row.example IS DISTINCT FROM item->'expectedSupport'->>'example'
      OR grammar_row.practice_config IS NOT NULL
      OR actual_examples IS DISTINCT FROM item->'expectedSupport'->'examples' THEN
      RAISE EXCEPTION '184 captured support changed: %',target_id;
    END IF;
  END LOOP;
  FOR task_item IN SELECT data FROM task_targets_184 LOOP
    SELECT * INTO task_row FROM lesson_grammar_task_items WHERE lesson_id=(task_item->>'lessonId')::uuid AND grammar_id=(task_item->>'grammarId')::uuid;
    IF NOT FOUND THEN RAISE EXCEPTION '184 missing task membership: %',task_item->>'grammarId'; END IF;
    IF task_row.instruction IS DISTINCT FROM task_item->>'expectedInstruction'
      OR task_row.required_count IS DISTINCT FROM (task_item->>'expectedRequiredCount')::int THEN
      RAISE EXCEPTION '184 captured task changed: %',task_item->>'grammarId';
    END IF;
  END LOOP;
  -- Detect added/removed task members without imposing an uncaptured sort order.
  IF EXISTS(SELECT 1 FROM lesson_grammar_task_items gi
    WHERE gi.lesson_id IN(SELECT lesson_id FROM task_targets_184)
      AND NOT EXISTS(SELECT 1 FROM task_targets_184 t WHERE t.lesson_id=gi.lesson_id AND t.grammar_id=gi.grammar_id)) THEN
    RAISE EXCEPTION '184 task membership set changed';
  END IF;
  -- Preserve full original records, including dialogue fields and example IDs.
  INSERT INTO n5_grammar_support_backup_184(grammar_id,before_grammar,before_examples)
    SELECT g.id,to_jsonb(g),COALESCE((SELECT jsonb_agg(to_jsonb(e) ORDER BY e.sort_order,e.id) FROM grammar_examples e WHERE e.grammar_id=g.id),'[]'::jsonb)
    FROM module_grammar g JOIN grammar_targets_184 t ON t.id=g.id;
  INSERT INTO n5_grammar_task_support_backup_184(lesson_id,grammar_id,before_item)
    SELECT gi.lesson_id,gi.grammar_id,to_jsonb(gi) FROM lesson_grammar_task_items gi JOIN task_targets_184 t USING(lesson_id,grammar_id);
  FOR target_id,item IN SELECT id,data FROM grammar_targets_184 LOOP
    UPDATE module_grammar SET example=item->'examples'->0->>'japanese',
      practice_config=NULLIF(item->'drills','null'::jsonb),updated_at=NOW() WHERE id=target_id;
    DELETE FROM grammar_examples WHERE grammar_id=target_id;
    INSERT INTO grammar_examples(grammar_id,japanese,highlight,indonesian,sort_order)
      SELECT target_id,e->>'japanese',e->>'highlight',e->>'indonesian',(ordinality-1)::int
      FROM jsonb_array_elements(item->'examples') WITH ORDINALITY AS examples(e,ordinality);
  END LOOP;
  UPDATE lesson_grammar_task_items gi SET instruction=t.data->>'instruction'
    FROM task_targets_184 t WHERE gi.lesson_id=t.lesson_id AND gi.grammar_id=t.grammar_id;
  UPDATE n5_grammar_support_backup_184 b SET after_grammar=to_jsonb(g),
    after_examples=COALESCE((SELECT jsonb_agg(to_jsonb(e) ORDER BY e.sort_order,e.id) FROM grammar_examples e WHERE e.grammar_id=g.id),'[]'::jsonb)
    FROM module_grammar g WHERE g.id=b.grammar_id;
  UPDATE n5_grammar_task_support_backup_184 b SET after_item=to_jsonb(gi)
    FROM lesson_grammar_task_items gi WHERE gi.lesson_id=b.lesson_id AND gi.grammar_id=b.grammar_id;
END
$support$;
