// Supporting uses of the existing chapter kanji. Sentence grammar is cumulative.
// These rows never add/remove kanji, vocabulary deck cards, or catalog readings.
// Kana keeps a supporting sentence from requiring later kanji to be deciphered.
const rows = [
  [4,'魚','魚','さかな','ikan','これは 魚です。','これは さかなです。','Ini ikan.'],
  [4,'本','本','ほん','buku','この 本は わたしのです。','この ほんは わたしのです。','Buku ini milik saya.'],
  [4,'本','日本語','にほんご','bahasa Jepang','これは 日本語の ほんです。','これは にほんごの ほんです。','Ini buku bahasa Jepang.'],
  [4,'花','花','はな','bunga','その 花は プレゼントです。','その はなは ぷれぜんとです。','Bunga itu hadiah.'],
  [5,'一','一時','いちじ','pukul satu','いま 一時です。','いま いちじです。','Sekarang pukul satu.'],
  [5,'二','二時','にじ','pukul dua','べんきょうは 二時からです。','べんきょうは にじからです。','Belajar mulai pukul dua.'],
  [5,'三','三時','さんじ','pukul tiga','べんきょうは 三時までです。','べんきょうは さんじまでです。','Belajar sampai pukul tiga.'],
  [5,'四','四時','よじ','pukul empat','いま 四時です。','いま よじです。','Sekarang pukul empat.'],
  [5,'五','五時','ごじ','pukul lima','しごとは 五時までです。','しごとは ごじまでです。','Pekerjaan berlangsung sampai pukul lima.'],
  [5,'六','六時','ろくじ','pukul enam','いま 六時です。','いま ろくじです。','Sekarang pukul enam.'],
  [5,'七','七時','しちじ','pukul tujuh','べんきょうは 七時からです。','べんきょうは しちじからです。','Belajar mulai pukul tujuh.'],
  [5,'八','八時','はちじ','pukul delapan','しごとは 八時からです。','しごとは はちじからです。','Pekerjaan mulai pukul delapan.'],
  [5,'九','九時','くじ','pukul sembilan','いま 九時です。','いま くじです。','Sekarang pukul sembilan.'],
  [5,'十','十時','じゅうじ','pukul sepuluh','べんきょうは 十時までです。','べんきょうは じゅうじまでです。','Belajar sampai pukul sepuluh.'],
  [6,'安','安い','やすい','murah','この ほんは 安いです。','この ほんは やすいです。','Buku ini murah.'],
  [6,'高','高い','たかい','mahal; tinggi','あの かばんは 高かったです。','あの かばんは たかかったです。','Tas itu dulu mahal.'],
  [6,'古','古い','ふるい','lama; tua (benda)','これは 古い じしょです。','これは ふるい じしょです。','Ini kamus lama.'],
  [6,'新','新しい','あたらしい','baru','この くつは 新しいです。','この くつは あたらしいです。','Sepatu ini baru.'],
  [6,'新','新聞','しんぶん','koran','これは あたらしい 新聞です。','これは あたらしい しんぶんです。','Ini koran baru.'],
  [6,'白','白い','しろい','putih','この かさは 白いです。','この かさは しろいです。','Payung ini putih.'],
  [6,'長','長い','ながい','panjang','これは 長い えんぴつです。','これは ながい えんぴつです。','Ini pensil panjang.'],
  [7,'男','男の人','おとこのひと','laki-laki','あの 男の人は しんせつです。','あの おとこのひとは しんせつです。','Laki-laki itu baik hati.'],
  [7,'女','女の人','おんなのひと','perempuan','あの 女の人は ゆうめいです。','あの おんなのひとは ゆうめいです。','Perempuan itu terkenal.'],
  [7,'気','元気','げんき','sehat; bersemangat','ははは 元気です。','ははは げんきです。','Ibu saya sehat.'],
  [8,'下','下','した','bawah','いすの 下に かばんが あります。','いすの したに かばんが あります。','Ada tas di bawah kursi.'],
  [8,'前','前','まえ','depan','えきの 前に ぎんこうが あります。','えきの まえに ぎんこうが あります。','Ada bank di depan stasiun.'],
  [8,'前','午前','ごぜん','pagi; a.m.','いま 午前 くじです。','いま ごぜん くじです。','Sekarang pukul sembilan pagi.'],
  [8,'外','外','そと','luar','せんせいは きょうしつの 外に います。','せんせいは きょうしつの そとに います。','Guru ada di luar kelas.'],
  [8,'間','間','あいだ','antara','ぎんこうと ホテルの 間に コンビニが あります。','ぎんこうと ほてるの あいだに こんびにが あります。','Ada minimarket di antara bank dan hotel.'],
  [8,'間','時間','じかん','waktu','べんきょうの 時間は いちじかんです。','べんきょうの じかんは いちじかんです。','Waktu belajar satu jam.'],
  [8,'右','右','みぎ','kanan','トイレは きょうしつの 右です。','といれは きょうしつの みぎです。','Toilet berada di kanan kelas.'],
  [8,'中','中','なか','dalam','かばんの 中に ほんが あります。','かばんの なかに ほんが あります。','Ada buku di dalam tas.'],
  [8,'左','左','ひだり','kiri','えきの 左に こうえんが あります。','えきの ひだりに こうえんが あります。','Ada taman di kiri stasiun.'],
  [8,'後','後ろ','うしろ','belakang','がっこうの 後ろに やまが あります。','がっこうの うしろに やまが あります。','Ada gunung di belakang sekolah.'],
  [8,'後','午後','ごご','sore; p.m.','いま 午後 さんじです。','いま ごご さんじです。','Sekarang pukul tiga sore.'],
  [8,'上','上','うえ','atas','つくえの 上に かぎが あります。','つくえの うえに かぎが あります。','Ada kunci di atas meja.'],
  [9,'車電','電車','でんしゃ','kereta','電車で がっこうへ いきます。','でんしゃで がっこうへ いきます。','Saya pergi ke sekolah naik kereta.'],
  [9,'車','車','くるま','mobil','ちちは 車で かいしゃへ いきます。','ちちは くるまで かいしゃへ いきます。','Ayah saya pergi ke kantor naik mobil.'],
  [9,'東','東','ひがし','timur','えきは がっこうの 東に あります。','えきは がっこうの ひがしに あります。','Stasiun ada di sebelah timur sekolah.'],
  [9,'道','道','みち','jalan','この 道は ながいです。','この みちは ながいです。','Jalan ini panjang.'],
  [9,'駅','駅','えき','stasiun','うちから 駅まで あるきます。','うちから えきまで あるきます。','Saya berjalan dari rumah sampai stasiun.'],
  [9,'行','行きます','いきます','pergi','ともだちと きょうとへ 行きます。','ともだちと きょうとへ いきます。','Saya pergi ke Kyoto bersama teman.'],
  [9,'西','西','にし','barat','ホテルは えきの 西に あります。','ほてるは えきの にしに あります。','Hotel ada di sebelah barat stasiun.'],
  [9,'北','北','きた','utara','がっこうは えきの 北に あります。','がっこうは えきの きたに あります。','Sekolah ada di sebelah utara stasiun.'],
  [9,'南','南','みなみ','selatan','こうえんは えきの 南に あります。','こうえんは えきの みなみに あります。','Taman ada di sebelah selatan stasiun.'],
  [10,'見','見ます','みます','melihat; menonton','まいばん テレビを 見ます。','まいばん てれびを みます。','Saya menonton televisi setiap malam.'],
  [10,'読','読みます','よみます','membaca','まいあさ しんぶんを 読みます。','まいあさ しんぶんを よみます。','Saya membaca koran setiap pagi.'],
  [10,'書','書きます','かきます','menulis','きのう ともだちに てがみを 書きました。','きのう ともだちに てがみを かきました。','Kemarin saya menulis surat kepada teman.'],
  [11,'年','一年','いちねん','satu tahun','にほんごを 一年 べんきょうしました。','にほんごを いちねん べんきょうしました。','Saya belajar bahasa Jepang selama satu tahun.'],
  [11,'百','百円','ひゃくえん','seratus yen','この パンは 百円です。','この ぱんは ひゃくえんです。','Roti ini harganya seratus yen.'],
  [11,'百','三百円','さんびゃくえん','tiga ratus yen','コーヒーは 三百円です。','こーひーは さんびゃくえんです。','Kopi harganya tiga ratus yen.'],
  [11,'午','午前','ごぜん','pagi; a.m.','午前 くじから べんきょうします。','ごぜん くじから べんきょうします。','Saya belajar mulai pukul sembilan pagi.'],
  [11,'午','午後','ごご','sore; p.m.','いま 午後 さんじです。','いま ごご さんじです。','Sekarang pukul tiga sore.'],
  [11,'半','半','はん','setengah (jam)','いま しちじ半です。','いま しちじはんです。','Sekarang pukul setengah delapan.'],
  [11,'半','半分','はんぶん','setengah bagian','ケーキを 半分 たべました。','けーきを はんぶん たべました。','Saya makan setengah kue.'],
  [11,'週毎','毎週','まいしゅう','setiap minggu','毎週 としょかんへ いきます。','まいしゅう としょかんへ いきます。','Saya pergi ke perpustakaan setiap minggu.'],
  [11,'週','一週間','いっしゅうかん','satu minggu','やすみは 一週間です。','やすみは いっしゅうかんです。','Liburnya satu minggu.'],
  [11,'万','一万円','いちまんえん','sepuluh ribu yen','この とけいは 一万円です。','この とけいは いちまんえんです。','Jam ini harganya sepuluh ribu yen.'],
  [11,'千','千円','せんえん','seribu yen','この ほんは 千円です。','この ほんは せんえんです。','Buku ini harganya seribu yen.'],
  [11,'千','三千円','さんぜんえん','tiga ribu yen','この かさは 三千円です。','この かさは さんぜんえんです。','Payung ini harganya tiga ribu yen.'],
  [11,'毎','毎日','まいにち','setiap hari','毎日 みずを のみます。','まいにち みずを のみます。','Saya minum air setiap hari.'],
  [12,'食','食べます','たべます','makan','あさごはんを 食べて、がっこうへ いきます。','あさごはんを たべて、がっこうへ いきます。','Saya sarapan, lalu pergi ke sekolah.'],
  [12,'飲','飲みます','のみます','minum','みずを 飲んでから、べんきょうします。','みずを のんでから、べんきょうします。','Setelah minum air, saya belajar.'],
  [14,'立','立つ','たつ','berdiri','ここに 立たないで ください。','ここに たたないで ください。','Tolong jangan berdiri di sini.'],
  [14,'休','休む','やすむ','beristirahat; libur','あしたは かいしゃを 休みます。','あしたは かいしゃを やすみます。','Besok saya tidak masuk kerja.'],
  [14,'休','休み','やすみ','libur; istirahat','きょうは 休みです。','きょうは やすみです。','Hari ini libur.'],
  [14,'入','入る','はいる','masuk','この へやに 入っても いいですか。','この へやに はいっても いいですか。','Bolehkah saya masuk ke ruangan ini?'],
  [14,'入','入口','いりぐち','pintu masuk','入口は あそこです。','いりぐちは あそこです。','Pintu masuk ada di sana.'],
  [14,'出','出る','でる','keluar','まいあさ うちを 出ます。','まいあさ うちを でます。','Saya keluar rumah setiap pagi.'],
  [14,'出','出口','でぐち','pintu keluar','出口は みぎです。','でぐちは みぎです。','Pintu keluar ada di kanan.'],
  [15,'言','言う','いう','berkata; mengucapkan','おなまえを 言って ください。','おなまえを いって ください。','Tolong sebutkan nama Anda.'],
  [15,'話','話す','はなす','berbicara','てんいんと にほんごで 話します。','てんいんと にほんごで はなします。','Saya berbicara dalam bahasa Jepang dengan pegawai toko.'],
  [15,'聞','聞く','きく','mendengarkan; bertanya','てんいんに ねだんを 聞きます。','てんいんに ねだんを ききます。','Saya menanyakan harga kepada pegawai toko.'],
  [15,'買','買う','かう','membeli','この みせで おみやげを 買います。','この みせで おみやげを かいます。','Saya membeli oleh-oleh di toko ini.'],
  [15,'店','店','みせ','toko','この 店は くじからです。','この みせは くじからです。','Toko ini buka mulai pukul sembilan.'],
  [15,'店','店員','てんいん','pegawai toko','この 店員は とても しんせつです。','この てんいんは とても しんせつです。','Pegawai toko ini sangat baik hati.'],
  [15,'円','円','えん','yen','おかいけいは ごひゃく円です。','おかいけいは ごひゃくえんです。','Total tagihannya lima ratus yen.'],
  [15,'会社','会社','かいしゃ','perusahaan; kantor','ちちは この 会社で はたらいています。','ちちは この かいしゃで はたらいています。','Ayah saya bekerja di perusahaan ini.'],
  [16,'日','日曜日','にちようび','Minggu','日曜日に ともだちと あいます。','にちようびに ともだちと あいます。','Saya bertemu teman pada hari Minggu.'],
  [16,'日','一日','ついたち','tanggal satu','かいぎは しがつ 一日です。','かいぎは しがつ ついたちです。','Rapatnya tanggal satu April.'],
  [16,'月','月曜日','げつようび','Senin','月曜日に テストが あります。','げつようびに てすとが あります。','Ada ujian pada hari Senin.'],
  [16,'月','四月','しがつ','April','がっこうは 四月に はじまります。','がっこうは しがつに はじまります。','Sekolah mulai pada bulan April.'],
  [16,'火','火曜日','かようび','Selasa','火曜日は かいぎが ありません。','かようびは かいぎが ありません。','Tidak ada rapat pada hari Selasa.'],
  [16,'水','水曜日','すいようび','Rabu','水曜日に にほんごを べんきょうします。','すいようびに にほんごを べんきょうします。','Saya belajar bahasa Jepang pada hari Rabu.'],
  [16,'木','木曜日','もくようび','Kamis','木曜日は やすみです。','もくようびは やすみです。','Hari Kamis libur.'],
  [16,'金','金曜日','きんようび','Jumat','金曜日に ともだちと ごはんを たべます。','きんようびに ともだちと ごはんを たべます。','Saya makan bersama teman pada hari Jumat.'],
  [16,'金','お金','おかね','uang','さいふに お金が あります。','さいふに おかねが あります。','Ada uang di dalam dompet.'],
  [16,'土','土曜日','どようび','Sabtu','土曜日に こうえんへ いきます。','どようびに こうえんへ いきます。','Saya pergi ke taman pada hari Sabtu.'],
  [16,'時','時間','じかん','waktu','かいぎの 時間は ごご さんじです。','かいぎの じかんは ごご さんじです。','Waktu rapatnya pukul tiga sore.'],
  [16,'時','四時','よじ','pukul empat','かいぎは 四時までです。','かいぎは よじまでです。','Rapat berlangsung sampai pukul empat.'],
  [16,'分','五分','ごふん','lima menit','えきから がっこうまで あるいて 五分です。','えきから がっこうまで あるいて ごふんです。','Dari stasiun ke sekolah lima menit berjalan kaki.'],
  [16,'分','十分','じゅっぷん','sepuluh menit','やすみじかんは 十分です。','やすみじかんは じゅっぷんです。','Waktu istirahat sepuluh menit.'],
  [17,'子','子ども','こども','anak','子どもは サッカーが すきです。','こどもは さっかーが すきです。','Anak itu suka sepak bola.'],
  [17,'父','父','ちち','ayah saya','父は つりが すきです。','ちちは つりが すきです。','Ayah saya suka memancing.'],
  [17,'母','母','はは','ibu saya','母は りょうりが じょうずです。','ははは りょうりが じょうずです。','Ibu saya pandai memasak.'],
  [17,'友','友だち','ともだち','teman','友だちと テニスを します。','ともだちと てにすを します。','Saya bermain tenis bersama teman.'],
  [17,'手','上手','じょうず','pandai','たなかさんは ピアノが 上手です。','たなかさんは ぴあのが じょうずです。','Tanaka pandai bermain piano.'],
  [17,'手','手','て','tangan','手を あらってから、りょうりを します。','てを あらってから、りょうりを します。','Setelah mencuci tangan, saya memasak.'],
  [17,'足','足','あし','kaki','足が いたいです。','あしが いたいです。','Kaki saya sakit.'],
  [17,'口','口','くち','mulut','口を あけて ください。','くちを あけて ください。','Tolong buka mulut.'],
  [17,'口','入口','いりぐち','pintu masuk','えいがかんの 入口で ともだちを まちます。','えいがかんの いりぐちで ともだちを まちます。','Saya menunggu teman di pintu masuk bioskop.'],
  [17,'目','目','め','mata','目が いたいです。','めが いたいです。','Mata saya sakit.'],
  [17,'耳','耳','みみ','telinga','みぎの 耳が いたいです。','みぎの みみが いたいです。','Telinga kanan saya sakit.'],
  [18,'大','大きい','おおきい','besar','この かばんは その かばんより 大きいです。','この かばんは その かばんより おおきいです。','Tas ini lebih besar daripada tas itu.'],
  [18,'大','大学','だいがく','universitas','大学は がっこうより とおいです。','だいがくは がっこうより とおいです。','Universitas lebih jauh daripada sekolah.'],
  [18,'小','小さい','ちいさい','kecil','あかい かばんが いちばん 小さいです。','あかい かばんが いちばん ちいさいです。','Tas merah paling kecil.'],
  [18,'多','多い','おおい','banyak','この まちは あの まちより ひとが 多いです。','この まちは あの まちより ひとが おおいです。','Orang di kota ini lebih banyak daripada di kota itu.'],
  [18,'少','少ない','すくない','sedikit','きょうは きのうより しごとが 少ないです。','きょうは きのうより しごとが すくないです。','Pekerjaan hari ini lebih sedikit daripada kemarin.'],
  [18,'少','少し','すこし','sedikit','にほんごが 少し できます。','にほんごが すこし できます。','Saya bisa sedikit bahasa Jepang.'],
  [19,'雨','雨','あめ','hujan','きょうは 雨です。あしたは さんぽしたいです。','きょうは あめです。あしたは さんぽしたいです。','Hari ini hujan. Besok saya ingin berjalan-jalan.'],
  [19,'天','天気','てんき','cuaca','きょうは いい 天気です。','きょうは いい てんきです。','Cuaca hari ini bagus.'],
  [19,'空','空','そら','langit','空が あおいです。しゃしんを とりたいです。','そらが あおいです。しゃしんを とりたいです。','Langit biru. Saya ingin memotretnya.'],
  [19,'空','空港','くうこう','bandara','あした 空港へ いく よていです。','あした くうこうへ いく よていです。','Saya dijadwalkan pergi ke bandara besok.'],
  [19,'山','山','やま','gunung','なつやすみに 山へ いきたいです。','なつやすみに やまへ いきたいです。','Saya ingin pergi ke gunung pada liburan musim panas.'],
  [19,'川','川','かわ','sungai','川の ちかくで キャンプを する つもりです。','かわの ちかくで きゃんぷを する つもりです。','Saya berniat berkemah di dekat sungai.'],
  [20,'来','来る','くる','datang','きのう ともだちが うちに 来ました。','きのう ともだちが うちに きました。','Kemarin teman datang ke rumah saya.'],
  [20,'来','来年','らいねん','tahun depan','にほんへ いったことが あります。来年も いきたいです。','にほんへ いったことが あります。らいねんも いきたいです。','Saya pernah ke Jepang. Tahun depan saya ingin pergi lagi.'],
  [20,'令','令和','れいわ','Reiwa (nama era Jepang)','この ほんは 令和 がんねんに かいました。','この ほんは れいわ がんねんに かいました。','Saya membeli buku ini pada tahun pertama era Reiwa.'],
];

export function n5ChapterKanjiSupport(character, chapter) {
  return rows.filter(([bab, characters]) => bab === chapter && characters.includes(character))
    .map(([, , japanese, reading, indonesian, exampleJapanese, exampleReading, exampleIndonesian]) => ({
      japanese, reading, indonesian, exampleJapanese, exampleReading, exampleIndonesian,
    }));
}

export const n5KanjiSupportInventory = rows.map(([chapter, characters, japanese]) => ({ chapter, characters, japanese }));
