-- 007_lesson_types.sql
-- Expand lesson.type enum to match new pedagogical flow per bab:
-- intro → kosakata → kanji → grammar → praktik → review
--
-- 'quiz' is retired in favor of 'review' (end-of-bab mini-kuis with 70% threshold).
-- 'video' and 'text' are kept as legacy types so existing rows don't break;
-- admin UI only offers the 6 new types for future lessons.

-- Drop old CHECK constraint (name generated by Postgres; find & drop dynamically).
DO $$
DECLARE
  c_name TEXT;
BEGIN
  SELECT conname INTO c_name
  FROM pg_constraint
  WHERE conrelid = 'lessons'::regclass
    AND contype = 'c'
    AND pg_get_constraintdef(oid) LIKE '%type%IN%video%quiz%text%';
  IF c_name IS NOT NULL THEN
    EXECUTE 'ALTER TABLE lessons DROP CONSTRAINT ' || quote_ident(c_name);
  END IF;
END $$;

-- Migrate existing 'quiz' → 'review' (semantic equivalent).
UPDATE lessons SET type = 'review' WHERE type = 'quiz';

-- New CHECK: 6 new types + 2 legacy (video, text) kept for gradual migration.
ALTER TABLE lessons
  ADD CONSTRAINT lessons_type_check
  CHECK (type IN ('intro','kosakata','kanji','grammar','praktik','review','video','text'));
