-- N4 cards use N5's concise pattern / function / separate notes format.
-- Generated by backend/scripts/build-n4-pattern-format.mjs.
-- Only pattern and meaning change. IDs, notes, examples, dialogues, drills,
-- lesson/task memberships, media and student history remain untouched.
CREATE TABLE IF NOT EXISTS n4_pattern_format_backup_193 (
  grammar_id uuid PRIMARY KEY, course_id uuid NOT NULL,
  before_fields jsonb NOT NULL, after_fields jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
DO $format$
DECLARE
  p jsonb := $plan${
  "courseId": "e22d819f-8526-4af6-a8c5-02258c12e6f0",
  "rows": [
    {
      "id": "3b41a238-b4f1-4327-a8e9-de69cdfbc804",
      "chapter": 1,
      "moduleId": "61d8ce65-5b6c-4dad-b75d-a3be800cb6c8",
      "moduleSlug": "n4-b01-menjelaskan-benda-kegiatan",
      "lessonId": "82faee90-5585-42cd-89cc-b5a3f8efb990",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "V bentuk biasa＋N 母が作った料理・使わない物",
        "meaning": "Penjelasan diletakkan sebelum benda: 母が作った料理 = masakan yang ibu buat. が menunjukkan pelaku dalam penjelasan. Gabungkan contoh negatif dan sedang berlangsung di sini; jangan memakai です／ます sebelum N."
      },
      "after": {
        "pattern": "V bentuk biasa＋N",
        "meaning": "menerangkan benda dengan klausa — “benda yang …”"
      }
    },
    {
      "id": "eded72e5-8a76-4a04-8264-436f976f1a2d",
      "chapter": 1,
      "moduleId": "61d8ce65-5b6c-4dad-b75d-a3be800cb6c8",
      "moduleSlug": "n4-b01-menjelaskan-benda-kegiatan",
      "lessonId": "21bb0803-1dde-4d65-a32d-ea13c3140ebd",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "V bentuk biasa＋の Vるのが好き／上手・Vるのは楽しい",
        "meaning": "Membicarakan kegiatan: 泳ぐのが好きです = saya suka berenang. の membuat kegiatan dapat menjadi hal yang dibicarakan."
      },
      "after": {
        "pattern": "〜のが好き／上手・〜のは〜",
        "meaning": "menjadikan kegiatan sebagai hal yang disukai, dikuasai, atau dinilai"
      }
    },
    {
      "id": "6abc2710-0e56-41d0-b8a7-e6cab423aa2a",
      "chapter": 1,
      "moduleId": "61d8ce65-5b6c-4dad-b75d-a3be800cb6c8",
      "moduleSlug": "n4-b01-menjelaskan-benda-kegiatan",
      "lessonId": "21bb0803-1dde-4d65-a32d-ea13c3140ebd",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "趣味は＋Vる＋ことです",
        "meaning": "Menyebutkan hobi: 趣味は泳ぐことです = hobi saya berenang. Gunakan kata kerja bentuk kamus sebelum こと."
      },
      "after": {
        "pattern": "趣味は〜ことです",
        "meaning": "menyatakan hobi — “hobi saya adalah …”"
      }
    },
    {
      "id": "54af13ff-97ed-4a59-a7af-5e899e581881",
      "chapter": 1,
      "moduleId": "61d8ce65-5b6c-4dad-b75d-a3be800cb6c8",
      "moduleSlug": "n4-b01-menjelaskan-benda-kegiatan",
      "lessonId": "21bb0803-1dde-4d65-a32d-ea13c3140ebd",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "の／こと：cara memilih 泳ぐのが好き・趣味は泳ぐことです V bentuk biasa＋のを見た／聞いた",
        "meaning": "Bandingkan pemakaian dalam kalimat. Untuk melihat atau mendengar kejadian, gunakan の: 鳥が飛ぶのを見ました = saya melihat burung terbang. の dan こと tidak selalu bisa saling menggantikan."
      },
      "after": {
        "pattern": "〜の／〜こと・〜のを見る／聞く",
        "meaning": "memilih nominalisasi dan menyatakan kejadian yang dilihat atau didengar"
      }
    },
    {
      "id": "ebf36f26-ec73-4a27-a8f3-cd7186f674c0",
      "chapter": 1,
      "moduleId": "61d8ce65-5b6c-4dad-b75d-a3be800cb6c8",
      "moduleSlug": "n4-b01-menjelaskan-benda-kegiatan",
      "lessonId": "82faee90-5585-42cd-89cc-b5a3f8efb990",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Aい＋の／Aな＋な＋の 赤いの・静かなの",
        "meaning": "Mengganti nama benda yang sudah jelas dari percakapan: 赤いの = yang merah; 静かなの = yang tenang."
      },
      "after": {
        "pattern": "〜いの／〜なの",
        "meaning": "menggantikan nama benda yang sudah jelas — “yang …”"
      }
    },
    {
      "id": "fedee2bc-5852-4576-a9e5-a764b6a38859",
      "chapter": 2,
      "moduleId": "d29f8cdb-e5e7-47f1-8f84-e0b840a17b70",
      "moduleSlug": "n4-b02-penjelasan-pendapat-kutipan",
      "lessonId": "bd69d351-2763-4c05-aee0-a01f50aaa086",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "普通形＋んです／のです N・Aな：だ→な＋んです",
        "meaning": "Menjelaskan konteks; termasuk なんです、たんです、ないんです、んですか. Kasual: V／Aい＋の？、N／Aな＋なの？."
      },
      "after": {
        "pattern": "〜んです／〜のです",
        "meaning": "memberi atau meminta penjelasan tentang suatu keadaan"
      }
    },
    {
      "id": "86615a65-a342-4cc0-a5cf-b441cdab27ec",
      "chapter": 2,
      "moduleId": "d29f8cdb-e5e7-47f1-8f84-e0b840a17b70",
      "moduleSlug": "n4-b02-penjelasan-pendapat-kutipan",
      "lessonId": "bd69d351-2763-4c05-aee0-a01f50aaa086",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "普通形＋んですが／んだけど N・Aな：なんですが／なんだけど",
        "meaning": "Mengantar pertanyaan, konsultasi, atau permintaan; bagian berikutnya dapat dilesapkan."
      },
      "after": {
        "pattern": "〜んですが／〜んだけど",
        "meaning": "mengantar pertanyaan, permintaan, atau konsultasi"
      }
    },
    {
      "id": "a60c9112-86e9-4e45-bbc1-bcbe9ebf7873",
      "chapter": 2,
      "moduleId": "d29f8cdb-e5e7-47f1-8f84-e0b840a17b70",
      "moduleSlug": "n4-b02-penjelasan-pendapat-kutipan",
      "lessonId": "4ac87534-1de1-4a7d-b189-b7cbdb595192",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "普通形＋と思う／と思っています",
        "meaning": "Menyatakan pendapat atau pemikiran. N dan Aな mempertahankan だ: 学生だと思います."
      },
      "after": {
        "pattern": "〜と思う／〜と思っている",
        "meaning": "menyatakan pendapat atau pemikiran — “menurut saya …”"
      }
    },
    {
      "id": "5e647985-8e3e-4c00-983c-34d3ad897283",
      "chapter": 2,
      "moduleId": "d29f8cdb-e5e7-47f1-8f84-e0b840a17b70",
      "moduleSlug": "n4-b02-penjelasan-pendapat-kutipan",
      "lessonId": "4ac87534-1de1-4a7d-b189-b7cbdb595192",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Kutipan＋と言う／と言っていた／と聞く Kutipan kasual：〜って",
        "meaning": "Mengutip atau melaporkan ucapan/informasi yang didengar; って dikenalkan sebagai variasi percakapan."
      },
      "after": {
        "pattern": "〜と言う／〜と言っていた／〜と聞く・〜って",
        "meaning": "mengutip ucapan atau melaporkan informasi yang didengar"
      }
    },
    {
      "id": "c96b9275-405d-4311-8e4a-195b54a0f2fa",
      "chapter": 2,
      "moduleId": "d29f8cdb-e5e7-47f1-8f84-e0b840a17b70",
      "moduleSlug": "n4-b02-penjelasan-pendapat-kutipan",
      "lessonId": "4ac87534-1de1-4a7d-b189-b7cbdb595192",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Nama＋という＋N",
        "meaning": "N yang bernama/disebut …; contoh: さくらという店."
      },
      "after": {
        "pattern": "〜という〜",
        "meaning": "menyebut nama — “yang bernama/disebut …”"
      }
    },
    {
      "id": "559a6627-fa7e-49f9-8b70-1edb9824993f",
      "chapter": 2,
      "moduleId": "d29f8cdb-e5e7-47f1-8f84-e0b840a17b70",
      "moduleSlug": "n4-b02-penjelasan-pendapat-kutipan",
      "lessonId": "4ac87534-1de1-4a7d-b189-b7cbdb595192",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "普通形＋かな／のかな N・Aな：Nかな／Nなのかな",
        "meaning": "Bertanya-tanya atau menyatakan keraguan pada diri sendiri."
      },
      "after": {
        "pattern": "〜かな／〜のかな",
        "meaning": "bertanya-tanya atau meragukan sesuatu dalam hati"
      }
    },
    {
      "id": "95cd10ea-b201-4c44-83de-1b7aeff42c07",
      "chapter": 3,
      "moduleId": "377eb9d6-2986-4893-980b-1fe92a871b9e",
      "moduleSlug": "n4-b03-waktu-urutan-kegiatan-beriringan",
      "lessonId": "5e2824e2-5d88-48cb-94cf-07bff41f7205",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "V普通形＋とき ／ Aい＋とき Aな＋なとき ／ N＋のとき",
        "meaning": "Ketika …; perbedaan Vるとき dan Vたとき mengikuti hubungan waktunya."
      },
      "after": {
        "pattern": "〜とき",
        "meaning": "menyatakan waktu terjadinya sesuatu — “ketika …”"
      }
    },
    {
      "id": "209d208b-c857-42a0-a43f-7bed2024bec8",
      "chapter": 3,
      "moduleId": "377eb9d6-2986-4893-980b-1fe92a871b9e",
      "moduleSlug": "n4-b03-waktu-urutan-kegiatan-beriringan",
      "lessonId": "5e2824e2-5d88-48cb-94cf-07bff41f7205",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Vる＋前に／Nの前に Vた＋後で／Nの後で",
        "meaning": "Sebelum dan sesudah; bandingkan dengan てから dari N5."
      },
      "after": {
        "pattern": "〜前に／〜後で",
        "meaning": "menyatakan urutan — “sebelum … / sesudah …”"
      }
    },
    {
      "id": "21fcd6c6-85c3-4a47-bf9d-64ffab9c8381",
      "chapter": 3,
      "moduleId": "377eb9d6-2986-4893-980b-1fe92a871b9e",
      "moduleSlug": "n4-b03-waktu-urutan-kegiatan-beriringan",
      "lessonId": "5e2824e2-5d88-48cb-94cf-07bff41f7205",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Vている＋間／間に Nの間／間に",
        "meaning": "間: berlangsung sepanjang interval; 間に: terjadi di dalam interval, tidak harus sepanjang waktunya."
      },
      "after": {
        "pattern": "〜間／〜間に",
        "meaning": "menyatakan kejadian sepanjang atau di dalam suatu rentang waktu"
      }
    },
    {
      "id": "78882d31-0895-4833-889d-a23c1c07171d",
      "chapter": 3,
      "moduleId": "377eb9d6-2986-4893-980b-1fe92a871b9e",
      "moduleSlug": "n4-b03-waktu-urutan-kegiatan-beriringan",
      "lessonId": "5e2824e2-5d88-48cb-94cf-07bff41f7205",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Waktu／Vる＋まで ／ Waktu／Vる＋までに",
        "meaning": "まで: berlanjut sampai batas; までに: tindakan selesai paling lambat pada batas itu."
      },
      "after": {
        "pattern": "〜まで／〜までに",
        "meaning": "membedakan batas berlangsungnya kegiatan dan tenggat penyelesaian"
      }
    },
    {
      "id": "773ded4a-7972-4a97-a07c-0b940908c219",
      "chapter": 3,
      "moduleId": "377eb9d6-2986-4893-980b-1fe92a871b9e",
      "moduleSlug": "n4-b03-waktu-urutan-kegiatan-beriringan",
      "lessonId": "a97483b5-98b5-49ed-8e5b-4e2e9d6bfa0a",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Vたり、Vたりする",
        "meaning": "Menyebut beberapa contoh kegiatan. Bentuk berasal dari Vた＋り; urutan bukan fokus utama."
      },
      "after": {
        "pattern": "〜たり、〜たりする",
        "meaning": "menyebut beberapa contoh kegiatan — “melakukan … dan …”"
      }
    },
    {
      "id": "c48ba199-7125-44ac-aa1f-d3e7cf426b2e",
      "chapter": 3,
      "moduleId": "377eb9d6-2986-4893-980b-1fe92a871b9e",
      "moduleSlug": "n4-b03-waktu-urutan-kegiatan-beriringan",
      "lessonId": "a97483b5-98b5-49ed-8e5b-4e2e9d6bfa0a",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Vます-stem＋ながら",
        "meaning": "Melakukan dua aktivitas bersamaan dengan pelaku yang sama; klausa akhir memuat aktivitas utama."
      },
      "after": {
        "pattern": "〜ながら",
        "meaning": "melakukan dua kegiatan bersamaan — “sambil …”"
      }
    },
    {
      "id": "51e2a621-f323-4a92-b859-ea769d636a9a",
      "chapter": 3,
      "moduleId": "377eb9d6-2986-4893-980b-1fe92a871b9e",
      "moduleSlug": "n4-b03-waktu-urutan-kegiatan-beriringan",
      "lessonId": "a97483b5-98b5-49ed-8e5b-4e2e9d6bfa0a",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Vない＋で、…",
        "meaning": "Melakukan B tanpa melakukan A; berbeda dari ないでください untuk larangan sopan."
      },
      "after": {
        "pattern": "〜ないで、〜",
        "meaning": "melakukan sesuatu tanpa melakukan tindakan lain"
      }
    },
    {
      "id": "820d48d1-48a8-47c9-b259-800de763b9c7",
      "chapter": 4,
      "moduleId": "c8c66af8-2437-4b15-bfeb-0879118ef48d",
      "moduleSlug": "n4-b04-kemampuan-persepsi",
      "lessonId": "c124d3ee-2fa9-41d4-aa36-28a2f83f8c17",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "可能形：G1 u → e＋る；G2 る → られる する→できる；来る→来られる（こられる）",
        "meaning": "Bentuk potensial: 書ける、食べられる. Sertakan negatif, lampau, dan objek が／を menurut konstruksi."
      },
      "after": {
        "pattern": "Bentuk potensial（可能形）",
        "meaning": "menyatakan kemampuan atau kemungkinan melakukan sesuatu"
      }
    },
    {
      "id": "9cbb1147-a95b-474c-8cef-388471c78075",
      "chapter": 4,
      "moduleId": "c8c66af8-2437-4b15-bfeb-0879118ef48d",
      "moduleSlug": "n4-b04-kemampuan-persepsi",
      "lessonId": "c124d3ee-2fa9-41d4-aa36-28a2f83f8c17",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Vる＋ことができる",
        "meaning": "Dapat melakukan …; bandingkan dengan bentuk potensial tanpa menganggap keduanya selalu identik konteksnya."
      },
      "after": {
        "pattern": "〜ことができる",
        "meaning": "menyatakan kemampuan — “dapat/bisa melakukan …”"
      }
    },
    {
      "id": "a71867c0-a1f5-45ec-bd43-9594fa317e20",
      "chapter": 4,
      "moduleId": "c8c66af8-2437-4b15-bfeb-0879118ef48d",
      "moduleSlug": "n4-b04-kemampuan-persepsi",
      "lessonId": "593ce3af-d379-446f-b81e-8fc7866576d9",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Nが見える／聞こえる Nが見られる／聞ける",
        "meaning": "Terlihat/terdengar secara perseptual vs dapat/kesempatan melihat atau mendengar."
      },
      "after": {
        "pattern": "〜が見える／聞こえる・〜が見られる／聞ける",
        "meaning": "membedakan persepsi alami dan kemampuan atau kesempatan melihat/mendengar"
      }
    },
    {
      "id": "34f79daf-5e22-43ce-9cf3-d1910b789609",
      "chapter": 4,
      "moduleId": "c8c66af8-2437-4b15-bfeb-0879118ef48d",
      "moduleSlug": "n4-b04-kemampuan-persepsi",
      "lessonId": "593ce3af-d379-446f-b81e-8fc7866576d9",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "音・声・におい・味＋がする",
        "meaning": "Terdengar bunyi/suara, tercium bau, atau terasa suatu rasa."
      },
      "after": {
        "pattern": "〜がする",
        "meaning": "menyatakan adanya bunyi, suara, bau, atau rasa"
      }
    },
    {
      "id": "6a20afd1-7455-47fe-9518-ed99e6b659cd",
      "chapter": 5,
      "moduleId": "bc1ef866-bb68-4404-8f08-f8cc3e621255",
      "moduleSlug": "n4-b05-niat-keputusan-kebiasaan",
      "lessonId": "d8061cf1-edeb-4a18-a854-f96003cbee4c",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "意向形＋（と思う／と思っている） G1 u→o＋う；G2 る→よう；しよう・来よう",
        "meaning": "Bentuk volisional untuk ajakan/tekad; ditambah と思う untuk niat. Konjugasi lengkap ada di lampiran."
      },
      "after": {
        "pattern": "Bentuk volisional・〜ようと思う／思っている",
        "meaning": "menyatakan ajakan, tekad, atau niat melakukan sesuatu"
      }
    },
    {
      "id": "05736360-eb7e-41ef-92cc-fa14ae95a7c6",
      "chapter": 5,
      "moduleId": "bc1ef866-bb68-4404-8f08-f8cc3e621255",
      "moduleSlug": "n4-b05-niat-keputusan-kebiasaan",
      "lessonId": "d8061cf1-edeb-4a18-a854-f96003cbee4c",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Vる／Vない＋ことにする／ことになる",
        "meaning": "Memutuskan sendiri vs menjadi keputusan/keadaan yang menentukan tindakan."
      },
      "after": {
        "pattern": "〜ことにする／〜ことになる",
        "meaning": "membedakan keputusan sendiri dan keputusan atau keadaan yang ditetapkan"
      }
    },
    {
      "id": "0fe354f8-3553-4fdc-963d-48697dacd11e",
      "chapter": 5,
      "moduleId": "bc1ef866-bb68-4404-8f08-f8cc3e621255",
      "moduleSlug": "n4-b05-niat-keputusan-kebiasaan",
      "lessonId": "4b87734e-e4fa-4bd7-93ee-ec2021aa6d7a",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Vる／Vない＋ことにしている",
        "meaning": "Menetapkan suatu kebiasaan/aturan untuk diri sendiri; bandingkan dengan keputusan satu kali ことにする."
      },
      "after": {
        "pattern": "〜ことにしている",
        "meaning": "menyatakan kebiasaan atau aturan yang ditetapkan untuk diri sendiri"
      }
    },
    {
      "id": "f198bd60-f4e2-4309-b27f-096a74102935",
      "chapter": 5,
      "moduleId": "bc1ef866-bb68-4404-8f08-f8cc3e621255",
      "moduleSlug": "n4-b05-niat-keputusan-kebiasaan",
      "lessonId": "4b87734e-e4fa-4bd7-93ee-ec2021aa6d7a",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Vる／Vない／V可能形＋ようになる",
        "meaning": "Perubahan kemampuan/kebiasaan. Sertakan Vなくなる untuk “tidak lagi”; makna mengikuti konteks, bukan selalu “jadi bisa”."
      },
      "after": {
        "pattern": "〜ようになる／〜なくなる",
        "meaning": "menyatakan perubahan kemampuan atau kebiasaan — “menjadi … / tidak lagi …”"
      }
    },
    {
      "id": "35ae0859-6fde-42d7-8f5d-31e10178dcb5",
      "chapter": 5,
      "moduleId": "bc1ef866-bb68-4404-8f08-f8cc3e621255",
      "moduleSlug": "n4-b05-niat-keputusan-kebiasaan",
      "lessonId": "4b87734e-e4fa-4bd7-93ee-ec2021aa6d7a",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Vる／Vない＋ようにする／ようにしている",
        "meaning": "Berusaha atau membiasakan agar melakukan/tidak melakukan."
      },
      "after": {
        "pattern": "〜ようにする／〜ようにしている",
        "meaning": "berusaha atau membiasakan diri untuk melakukan/tidak melakukan sesuatu"
      }
    },
    {
      "id": "6060cab0-e192-40cb-9e7f-71ca0973f18d",
      "chapter": 6,
      "moduleId": "d9db5f79-38e6-4dcf-ba46-9f29be362877",
      "moduleSlug": "n4-b06-mencoba-menyelesaikan-menanggapi-hasil",
      "lessonId": "81a1fb2a-2e2e-4cbf-9500-36d49b43cd2f",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Vて＋みる",
        "meaning": "Mencoba melakukan; てみたい adalah penerapan pola ini dengan たい, bukan pola baru."
      },
      "after": {
        "pattern": "〜てみる",
        "meaning": "mencoba melakukan sesuatu"
      }
    },
    {
      "id": "be008ffc-ce98-4337-8db9-4c36b660fc20",
      "chapter": 6,
      "moduleId": "d9db5f79-38e6-4dcf-ba46-9f29be362877",
      "moduleSlug": "n4-b06-mencoba-menyelesaikan-menanggapi-hasil",
      "lessonId": "81a1fb2a-2e2e-4cbf-9500-36d49b43cd2f",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Vて＋しまう てしまう→ちゃう；でしまう→じゃう",
        "meaning": "Selesai seluruhnya atau bernuansa terlanjur/tidak diharapkan; konteks menentukan penyesalan."
      },
      "after": {
        "pattern": "〜てしまう／〜ちゃう／〜じゃう",
        "meaning": "menyelesaikan seluruh tindakan atau menyatakan sesuatu yang terlanjur terjadi"
      }
    },
    {
      "id": "64e59ad7-df3a-436e-b766-ddf5b8d8492e",
      "chapter": 6,
      "moduleId": "d9db5f79-38e6-4dcf-ba46-9f29be362877",
      "moduleSlug": "n4-b06-mencoba-menyelesaikan-menanggapi-hasil",
      "lessonId": "f520201f-e281-4f38-80d9-324705a0af78",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Vて＋よかった ／ Vなくて＋よかった",
        "meaning": "Senang/lega karena melakukan atau tidak melakukan sesuatu."
      },
      "after": {
        "pattern": "〜てよかった／〜なくてよかった",
        "meaning": "merasa senang atau lega karena melakukan/tidak melakukan sesuatu"
      }
    },
    {
      "id": "1f385dcf-d1af-4bba-99f9-40aa1cd78b5a",
      "chapter": 6,
      "moduleId": "d9db5f79-38e6-4dcf-ba46-9f29be362877",
      "moduleSlug": "n4-b06-mencoba-menyelesaikan-menanggapi-hasil",
      "lessonId": "f520201f-e281-4f38-80d9-324705a0af78",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Vて＋すみません ／ Vなくて＋すみません",
        "meaning": "Meminta maaf atas tindakan atau tidak terlaksananya tindakan; negatif memakai なくて."
      },
      "after": {
        "pattern": "〜てすみません／〜なくてすみません",
        "meaning": "meminta maaf karena melakukan/tidak melakukan sesuatu"
      }
    },
    {
      "id": "e57880e8-761f-449c-8ea6-da9f802ace6e",
      "chapter": 7,
      "moduleId": "dd5c6d36-8dfb-4c1f-bf61-62a574229b1f",
      "moduleSlug": "n4-b07-verba-berpasangan-keadaan-persiapan",
      "lessonId": "22172988-3428-4d68-ade0-52b1c3814496",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Nを＋他動詞 ／ Nが＋自動詞",
        "meaning": "Verba transitif-intransitif: ドアを開ける／ドアが開く. Pasangan dipelajari sebagai kosakata terkait."
      },
      "after": {
        "pattern": "〜を＋verba transitif／〜が＋verba intransitif",
        "meaning": "membedakan tindakan pada benda dan perubahan atau kejadian pada benda"
      }
    },
    {
      "id": "0e4fc372-5e3f-479c-924b-f537405e893e",
      "chapter": 7,
      "moduleId": "dd5c6d36-8dfb-4c1f-bf61-62a574229b1f",
      "moduleSlug": "n4-b07-verba-berpasangan-keadaan-persiapan",
      "lessonId": "22172988-3428-4d68-ade0-52b1c3814496",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Nが＋自動詞ている",
        "meaning": "Keadaan hasil perubahan: ドアが開いている; perluasan terarah dari ている N5."
      },
      "after": {
        "pattern": "〜が＋verba intransitifている",
        "meaning": "menyatakan keadaan yang bertahan setelah suatu perubahan"
      }
    },
    {
      "id": "927f5138-3988-45d7-ab3a-d4eebfd9ae13",
      "chapter": 7,
      "moduleId": "dd5c6d36-8dfb-4c1f-bf61-62a574229b1f",
      "moduleSlug": "n4-b07-verba-berpasangan-keadaan-persiapan",
      "lessonId": "85aa72cb-5b3e-4740-86d8-21d31bb00932",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Nが＋他動詞てある Nを＋Vてある juga dipakai pada konteks persiapan",
        "meaning": "Hasil tindakan yang sengaja dilakukan masih ada; misalnya persiapan atau penataan."
      },
      "after": {
        "pattern": "〜てある",
        "meaning": "menyatakan hasil tindakan sengaja yang masih ada"
      }
    },
    {
      "id": "5b399f7d-1fdb-47ec-b4a1-728ace562e18",
      "chapter": 7,
      "moduleId": "dd5c6d36-8dfb-4c1f-bf61-62a574229b1f",
      "moduleSlug": "n4-b07-verba-berpasangan-keadaan-persiapan",
      "lessonId": "85aa72cb-5b3e-4740-86d8-21d31bb00932",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Vて＋おく ておく→とく；でおく→どく",
        "meaning": "Melakukan sebagai persiapan atau membiarkan keadaan tetap begitu."
      },
      "after": {
        "pattern": "〜ておく／〜とく／〜どく",
        "meaning": "melakukan persiapan atau membiarkan keadaan tetap begitu"
      }
    },
    {
      "id": "cdc54833-4399-44a8-a1c4-4802c5fda033",
      "chapter": 8,
      "moduleId": "52fa650c-2d46-4c5b-ad90-59f521b6d5e8",
      "moduleSlug": "n4-b08-arah-perkembangan-tahap-aktivitas",
      "lessonId": "73fe00f5-21e2-4105-8fd7-8467367fca74",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Vていく／Vてくる",
        "meaning": "Arah gerak atau perkembangan terhadap titik acuan; jelaskan kedua fungsi ruang dan waktu."
      },
      "after": {
        "pattern": "〜ていく／〜てくる",
        "meaning": "menyatakan arah gerak atau perkembangan terhadap titik acuan"
      }
    },
    {
      "id": "931b1e73-e2ba-4cb6-8744-997b9b5380da",
      "chapter": 8,
      "moduleId": "52fa650c-2d46-4c5b-ad90-59f521b6d5e8",
      "moduleSlug": "n4-b08-arah-perkembangan-tahap-aktivitas",
      "lessonId": "73fe00f5-21e2-4105-8fd7-8467367fca74",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Vます-stem＋始める／出す",
        "meaning": "Mulai melakukan/terjadi; 出す sering menonjolkan awal yang mendadak."
      },
      "after": {
        "pattern": "〜始める／〜出す",
        "meaning": "menyatakan awal kegiatan atau kejadian — “mulai …”"
      }
    },
    {
      "id": "4002889e-6ecf-4b6e-b4bd-86254ec5d5c1",
      "chapter": 8,
      "moduleId": "52fa650c-2d46-4c5b-ad90-59f521b6d5e8",
      "moduleSlug": "n4-b08-arah-perkembangan-tahap-aktivitas",
      "lessonId": "73fe00f5-21e2-4105-8fd7-8467367fca74",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Vます-stem＋続ける／終わる",
        "meaning": "Terus melakukan / selesai melakukan; bandingkan perkembangan tahap aktivitas."
      },
      "after": {
        "pattern": "〜続ける／〜終わる",
        "meaning": "menyatakan kelanjutan atau akhir kegiatan — “terus … / selesai …”"
      }
    },
    {
      "id": "daa05f6e-93ab-4f75-8c00-8ff7830e8e93",
      "chapter": 8,
      "moduleId": "52fa650c-2d46-4c5b-ad90-59f521b6d5e8",
      "moduleSlug": "n4-b08-arah-perkembangan-tahap-aktivitas",
      "lessonId": "9ab60515-2279-4982-b36e-2b59ea50d3ee",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Vるところだ／Vているところだ／Vたところだ",
        "meaning": "Akan segera, sedang tepat pada saat itu, dan baru saja selesai. Tiga variasi dalam satu keluarga pola."
      },
      "after": {
        "pattern": "〜るところ／〜ているところ／〜たところ",
        "meaning": "menyatakan tahap tindakan — “akan segera / sedang / baru saja …”"
      }
    },
    {
      "id": "2edf278e-e07f-436c-a0cd-86e13c3a87ad",
      "chapter": 8,
      "moduleId": "52fa650c-2d46-4c5b-ad90-59f521b6d5e8",
      "moduleSlug": "n4-b08-arah-perkembangan-tahap-aktivitas",
      "lessonId": "9ab60515-2279-4982-b36e-2b59ea50d3ee",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Vた＋ばかりだ",
        "meaning": "Merasa baru saja melakukan sesuatu; jarak waktu dinilai pembicara. Bandingkan dengan Vたところだ."
      },
      "after": {
        "pattern": "〜たばかり",
        "meaning": "menyatakan tindakan yang dirasa baru saja dilakukan"
      }
    },
    {
      "id": "0221a8e3-c36b-4545-bf1e-5358e4b21396",
      "chapter": 8,
      "moduleId": "52fa650c-2d46-4c5b-ad90-59f521b6d5e8",
      "moduleSlug": "n4-b08-arah-perkembangan-tahap-aktivitas",
      "lessonId": "9ab60515-2279-4982-b36e-2b59ea50d3ee",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "もうVた／Vました・まだVていない・まだVている",
        "meaning": "Sudah, belum, dan masih; bedakan keadaan selesai dengan berlangsungnya aktivitas."
      },
      "after": {
        "pattern": "もう〜た／まだ〜ていない／まだ〜ている",
        "meaning": "membedakan kegiatan yang sudah selesai, belum dilakukan, dan masih berlangsung"
      }
    },
    {
      "id": "9310a766-a8a7-4520-904d-e9adfa304a44",
      "chapter": 9,
      "moduleId": "034b3cc0-7f52-4cbe-83f3-3554b21092b4",
      "moduleSlug": "n4-b09-cara-kemudahan-perubahan-sifat",
      "lessonId": "7a4658c8-eb44-47de-ae41-9e464d5818d1",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Vます-stem＋方 Nをする → Nの仕方",
        "meaning": "Cara melakukan: 読み方、使い方、勉強の仕方. Sesuaikan partikel ketika menjadi frasa nomina."
      },
      "after": {
        "pattern": "〜方／〜の仕方",
        "meaning": "menyatakan cara melakukan sesuatu"
      }
    },
    {
      "id": "d9ac7146-30d2-4df3-9bcc-4061c297dfab",
      "chapter": 9,
      "moduleId": "034b3cc0-7f52-4cbe-83f3-3554b21092b4",
      "moduleSlug": "n4-b09-cara-kemudahan-perubahan-sifat",
      "lessonId": "7a4658c8-eb44-47de-ae41-9e464d5818d1",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Vます-stem＋やすい／にくい",
        "meaning": "Mudah atau sulit dilakukan; keduanya berkonjugasi seperti sifat い."
      },
      "after": {
        "pattern": "〜やすい／〜にくい",
        "meaning": "menyatakan sesuatu mudah atau sulit dilakukan"
      }
    },
    {
      "id": "ddd7b7eb-77fd-4fc0-8f96-7bcd27d5ca28",
      "chapter": 9,
      "moduleId": "034b3cc0-7f52-4cbe-83f3-3554b21092b4",
      "moduleSlug": "n4-b09-cara-kemudahan-perubahan-sifat",
      "lessonId": "7a4658c8-eb44-47de-ae41-9e464d5818d1",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Vます-stem＋すぎる Aい hapus い／Aな-stem＋すぎる",
        "meaning": "Terlalu/berlebihan; いい→よすぎる. Negatif dan bentuk lampau dari すぎる dipelajari sebagai variasi."
      },
      "after": {
        "pattern": "〜すぎる",
        "meaning": "menyatakan sesuatu berlebihan — “terlalu …”"
      }
    },
    {
      "id": "e5bad6e3-2a14-4549-a837-db3a4f3ff8c9",
      "chapter": 9,
      "moduleId": "034b3cc0-7f52-4cbe-83f3-3554b21092b4",
      "moduleSlug": "n4-b09-cara-kemudahan-perubahan-sifat",
      "lessonId": "1d3d803c-06da-4633-a070-14476482ead8",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Aい：い→く＋V／Aな-stem＋に＋V",
        "meaning": "Sifat menjadi keterangan cara: 早く歩く、静かに話す."
      },
      "after": {
        "pattern": "〜く＋V／〜に＋V",
        "meaning": "menerangkan cara melakukan tindakan dengan kata sifat"
      }
    },
    {
      "id": "0e4531c6-642d-498d-badc-3dbc4e855abd",
      "chapter": 9,
      "moduleId": "034b3cc0-7f52-4cbe-83f3-3554b21092b4",
      "moduleSlug": "n4-b09-cara-kemudahan-perubahan-sifat",
      "lessonId": "1d3d803c-06da-4633-a070-14476482ead8",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Aい：い→くする ／ Aな・N＋にする",
        "meaning": "Membuat sesuatu menjadi …; bandingkan dengan くなる／になる dan pilihan にする dari N5."
      },
      "after": {
        "pattern": "〜くする／〜にする",
        "meaning": "membuat sesuatu menjadi suatu keadaan"
      }
    },
    {
      "id": "da290fe5-88a8-40e0-8424-3a591df34111",
      "chapter": 9,
      "moduleId": "034b3cc0-7f52-4cbe-83f3-3554b21092b4",
      "moduleSlug": "n4-b09-cara-kemudahan-perubahan-sifat",
      "lessonId": "1d3d803c-06da-4633-a070-14476482ead8",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Aい hapus い／Aな-stem＋さ",
        "meaning": "Menominalkan derajat sifat: 高さ、便利さ; いい→よさ."
      },
      "after": {
        "pattern": "〜さ",
        "meaning": "mengubah kata sifat menjadi nama sifat atau ukuran derajatnya"
      }
    },
    {
      "id": "c61fa4fc-7998-4ad0-af86-1ce0da781ac9",
      "chapter": 10,
      "moduleId": "a43ebaa8-5865-4a51-953d-640167e2ad13",
      "moduleSlug": "n4-b10-alasan-kontras-konsesi",
      "lessonId": "ef235a5f-c681-4488-851e-0e63ea9069a5",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "普通形＋ので N・Aな非過去肯定：な＋ので",
        "meaning": "Karena/sebab; menyajikan latar alasan. Bukan hanya versi sopan dari から."
      },
      "after": {
        "pattern": "〜ので",
        "meaning": "memberi latar alasan — “karena/sebab …”"
      }
    },
    {
      "id": "ce6ba281-3e25-42ea-a34f-b2ef3e0402b4",
      "chapter": 10,
      "moduleId": "a43ebaa8-5865-4a51-953d-640167e2ad13",
      "moduleSlug": "n4-b10-alasan-kontras-konsesi",
      "lessonId": "ef235a5f-c681-4488-851e-0e63ea9069a5",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "普通形＋し、普通形＋し、…",
        "meaning": "Menyebut alasan atau sifat secara bertambah; N・Aな memakai だし."
      },
      "after": {
        "pattern": "〜し、〜し",
        "meaning": "menyebut beberapa alasan atau sifat secara bertambah"
      }
    },
    {
      "id": "8aea44c1-727a-4bd6-83dc-4b5fca2371f3",
      "chapter": 10,
      "moduleId": "a43ebaa8-5865-4a51-953d-640167e2ad13",
      "moduleSlug": "n4-b10-alasan-kontras-konsesi",
      "lessonId": "b55f3a04-6a23-4eed-a1a7-2f391abfe20e",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "普通形＋けど／けれど／けれども",
        "meaning": "Tetapi/meskipun; juga pengantar atau pelembut. N・Aな memakai だけど. Ragam tutur berbeda."
      },
      "after": {
        "pattern": "〜けど／〜けれど／〜けれども",
        "meaning": "menyatakan pertentangan atau menghaluskan pengantar pembicaraan"
      }
    },
    {
      "id": "f1770505-1e8e-4eb3-9960-ee23a32ae9dc",
      "chapter": 10,
      "moduleId": "a43ebaa8-5865-4a51-953d-640167e2ad13",
      "moduleSlug": "n4-b10-alasan-kontras-konsesi",
      "lessonId": "b55f3a04-6a23-4eed-a1a7-2f391abfe20e",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "普通形＋のに N・Aな非過去肯定：な＋のに",
        "meaning": "Padahal; hasil bertentangan dengan yang diharapkan pembicara."
      },
      "after": {
        "pattern": "〜のに",
        "meaning": "menyatakan hasil yang berbeda dari harapan — “padahal …”"
      }
    },
    {
      "id": "e66f2ffc-6a6b-4e64-a6c7-05ba566759fb",
      "chapter": 10,
      "moduleId": "a43ebaa8-5865-4a51-953d-640167e2ad13",
      "moduleSlug": "n4-b10-alasan-kontras-konsesi",
      "lessonId": "ef235a5f-c681-4488-851e-0e63ea9069a5",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Vて／Vなくて、… Aいくて・Aな／Nで、…",
        "meaning": "Sebab/akibat atau keadaan terkait. Bedakan なくて karena tidak … dengan ないで tanpa melakukan …."
      },
      "after": {
        "pattern": "〜て／〜なくて・〜くて／〜で",
        "meaning": "menghubungkan sebab, akibat, atau keadaan yang berkaitan"
      }
    },
    {
      "id": "561023dd-9854-4436-b113-370d72b42307",
      "chapter": 10,
      "moduleId": "a43ebaa8-5865-4a51-953d-640167e2ad13",
      "moduleSlug": "n4-b10-alasan-kontras-konsesi",
      "lessonId": "b55f3a04-6a23-4eed-a1a7-2f391abfe20e",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Vて＋も／Aいくても Aな・N＋でも／negatif：なくても",
        "meaning": "Meskipun/walaupun …; dapat bermakna konsesi faktual atau hipotetis. Bedakan dari のに yang menonjolkan harapan yang meleset."
      },
      "after": {
        "pattern": "〜ても／〜でも／〜なくても",
        "meaning": "menyatakan konsesi — “meskipun/walaupun …”"
      }
    },
    {
      "id": "4d3efc88-0326-40da-9745-e84d5e385949",
      "chapter": 11,
      "moduleId": "87c74265-8edd-4c2f-abe8-033204f66bbc",
      "moduleSlug": "n4-b11-dugaan-informasi-orang-lain",
      "lessonId": "c1cb8777-bcb2-46da-ab03-cd5147b728b8",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Vます-stem＋そうだ Aい hapus い／Aな-stem＋そうだ",
        "meaning": "Kelihatannya/akan segera; penampakan. Pengecualian: よさそう、なさそう. N tidak langsung memakai pola ini."
      },
      "after": {
        "pattern": "〜そうだ（penampakan）",
        "meaning": "menyatakan kesan yang tampak — “kelihatannya … / akan segera …”"
      }
    },
    {
      "id": "b53db883-b610-4abc-92d8-1a8e720f52ce",
      "chapter": 11,
      "moduleId": "87c74265-8edd-4c2f-abe8-033204f66bbc",
      "moduleSlug": "n4-b11-dugaan-informasi-orang-lain",
      "lessonId": "c1cb8777-bcb2-46da-ab03-cd5147b728b8",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "普通形＋そうだ／そうです N・Aな非過去肯定：だそうだ",
        "meaning": "Katanya/saya dengar; kabar. Bedakan 降るそうだ dengan 降りそうだ."
      },
      "after": {
        "pattern": "〜そうだ（kabar）",
        "meaning": "melaporkan informasi — “katanya/saya dengar …”"
      }
    },
    {
      "id": "7445d762-bed3-4cb9-8f7b-8c6f72211cd3",
      "chapter": 11,
      "moduleId": "87c74265-8edd-4c2f-abe8-033204f66bbc",
      "moduleSlug": "n4-b11-dugaan-informasi-orang-lain",
      "lessonId": "c1cb8777-bcb2-46da-ab03-cd5147b728b8",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "V・Aい普通形／N・Aな-stem＋らしい",
        "meaning": "Kabarnya/tampaknya berdasarkan informasi; khusus fungsi inferensi, bukan “khas …”."
      },
      "after": {
        "pattern": "〜らしい",
        "meaning": "menyatakan dugaan berdasarkan informasi — “kabarnya/tampaknya …”"
      }
    },
    {
      "id": "481653aa-ad49-4988-92d0-3dc088229c7f",
      "chapter": 11,
      "moduleId": "87c74265-8edd-4c2f-abe8-033204f66bbc",
      "moduleSlug": "n4-b11-dugaan-informasi-orang-lain",
      "lessonId": "0b297a0e-60a4-4ba3-8919-8ec90ab97f79",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "V・Aい普通形／N・Aな-stem＋かもしれない",
        "meaning": "Mungkin …; sertakan bentuk sopan かもしれません dan bentuk lampau/negatif pada klausa."
      },
      "after": {
        "pattern": "〜かもしれない／〜かもしれません",
        "meaning": "menyatakan kemungkinan — “mungkin …”"
      }
    },
    {
      "id": "be145704-49e9-4840-8248-e05e2b363189",
      "chapter": 11,
      "moduleId": "87c74265-8edd-4c2f-abe8-033204f66bbc",
      "moduleSlug": "n4-b11-dugaan-informasi-orang-lain",
      "lessonId": "0b297a0e-60a4-4ba3-8919-8ec90ab97f79",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "V・Aい普通形／N・Aな-stem＋でしょう／だろう",
        "meaning": "Perkiraan atau meminta konfirmasi menurut konteks dan intonasi; bedakan ragam tutur."
      },
      "after": {
        "pattern": "〜でしょう／〜だろう",
        "meaning": "menyatakan perkiraan atau meminta konfirmasi sesuai konteks"
      }
    },
    {
      "id": "9c82c41d-3152-4bc9-8a2f-9c22a69e1f05",
      "chapter": 11,
      "moduleId": "87c74265-8edd-4c2f-abe8-033204f66bbc",
      "moduleSlug": "n4-b11-dugaan-informasi-orang-lain",
      "lessonId": "0b297a0e-60a4-4ba3-8919-8ec90ab97f79",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "V・Aい普通形／Aな＋な／N＋の＋はずだ Pola sambungan yang sama＋はずがない",
        "meaning": "Diperkirakan demikian berdasarkan alasan / seharusnya tidak mungkin demikian. Bukan kewajiban moral."
      },
      "after": {
        "pattern": "〜はずだ／〜はずがない",
        "meaning": "menyatakan perkiraan beralasan atau ketidakmungkinan — “mestinya …”"
      }
    },
    {
      "id": "b3b6d347-3555-432f-86a1-3979148bc6a3",
      "chapter": 12,
      "moduleId": "64a54a15-677d-4384-95c4-c2b22d8e717f",
      "moduleSlug": "n4-b12-kemiripan-perasaan-keinginan",
      "lessonId": "a9d4331c-63a2-41c1-b04f-1a4be36e3a2b",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "V・Aい普通形／Aな＋な／N＋の＋ようだ Nのような＋N／Nのように＋V・A",
        "meaning": "Sepertinya berdasarkan tanda atau mirip …; termasuk bentuk penjelas nomina/cara."
      },
      "after": {
        "pattern": "〜ようだ／〜ような／〜ように",
        "meaning": "menyatakan dugaan berdasarkan tanda atau kemiripan — “sepertinya/seperti …”"
      }
    },
    {
      "id": "feaf0131-8273-4b0e-9bac-cc4fb99a58ff",
      "chapter": 12,
      "moduleId": "64a54a15-677d-4384-95c4-c2b22d8e717f",
      "moduleSlug": "n4-b12-kemiripan-perasaan-keinginan",
      "lessonId": "a9d4331c-63a2-41c1-b04f-1a4be36e3a2b",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "V・Aい普通形／N・Aな-stem＋みたいだ Nみたいな＋N／Nみたいに＋V・A",
        "meaning": "Sepertinya/mirip; bentuk percakapan. みたい berbeda dari keinginan 見たい."
      },
      "after": {
        "pattern": "〜みたいだ／〜みたいな／〜みたいに",
        "meaning": "menyatakan dugaan atau kemiripan dalam percakapan"
      }
    },
    {
      "id": "07415387-6b6f-4eb7-a00e-0b321d59055f",
      "chapter": 12,
      "moduleId": "64a54a15-677d-4384-95c4-c2b22d8e717f",
      "moduleSlug": "n4-b12-kemiripan-perasaan-keinginan",
      "lessonId": "a9d4331c-63a2-41c1-b04f-1a4be36e3a2b",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "そうな＋N ／ そうに＋V",
        "meaning": "Pengembangan そう penampakan untuk menerangkan nomina/cara. Contoh: おいしそうな料理、楽しそうに話す."
      },
      "after": {
        "pattern": "〜そうな／〜そうに",
        "meaning": "menerangkan benda atau tindakan berdasarkan penampakannya"
      }
    },
    {
      "id": "06e1aa0a-6abf-4e7c-8b8d-e4bdb6cb9dbb",
      "chapter": 12,
      "moduleId": "64a54a15-677d-4384-95c4-c2b22d8e717f",
      "moduleSlug": "n4-b12-kemiripan-perasaan-keinginan",
      "lessonId": "5208e79c-3d92-4c63-a2c8-3c9bec39dcb3",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Aい hapus い／Aな-stem＋がる",
        "meaning": "Menunjukkan tanda merasa …; terbatas pada sifat tertentu, misalnya 怖がる、嫌がる. Bukan semua sifat."
      },
      "after": {
        "pattern": "〜がる",
        "meaning": "menyatakan tanda perasaan yang diperlihatkan seseorang"
      }
    },
    {
      "id": "ba4cb20f-1d8c-4e1d-b363-7e27f0169b61",
      "chapter": 12,
      "moduleId": "64a54a15-677d-4384-95c4-c2b22d8e717f",
      "moduleSlug": "n4-b12-kemiripan-perasaan-keinginan",
      "lessonId": "5208e79c-3d92-4c63-a2c8-3c9bec39dcb3",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Vます-stem＋たがる／たがっている Nを欲しがる／欲しがっている",
        "meaning": "Menunjukkan keinginan melakukan atau memiliki. Bentuk 〜がっている menjelaskan keadaan yang terlihat."
      },
      "after": {
        "pattern": "〜たがる／〜たがっている・〜を欲しがる",
        "meaning": "menyatakan keinginan melakukan atau memiliki yang terlihat pada seseorang"
      }
    },
    {
      "id": "84c2f6be-45ed-48e4-8f27-b84bcbaa2da9",
      "chapter": 13,
      "moduleId": "d0d67a65-b304-4b3d-b6e6-3e1239473a67",
      "moduleSlug": "n4-b13-pengandaian-to-tara",
      "lessonId": "827bdfa1-d7d2-4980-a65a-213714e9c0fb",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "V・Aい普通形＋と、… N・Aな非過去肯定：だと",
        "meaning": "Jika/ketika A, B terjadi secara lazim, otomatis, atau sebagai hasil pengamatan."
      },
      "after": {
        "pattern": "〜と、〜",
        "meaning": "menyatakan syarat atau hasil yang lazim, otomatis, atau teramati"
      }
    },
    {
      "id": "ac1d8893-9a5f-4f4c-a65c-a2b240e819a9",
      "chapter": 13,
      "moduleId": "d0d67a65-b304-4b3d-b6e6-3e1239473a67",
      "moduleSlug": "n4-b13-pengandaian-to-tara",
      "lessonId": "827bdfa1-d7d2-4980-a65a-213714e9c0fb",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Vた・Aかった・N／Aなだった＋ら Negatif：なかった＋ら",
        "meaning": "Jika/setelah …; termasuk もし〜たら dan hasil yang baru ditemukan. Semua variasi dalam satu keluarga."
      },
      "after": {
        "pattern": "〜たら",
        "meaning": "menyatakan syarat atau urutan — “jika/setelah …”"
      }
    },
    {
      "id": "165c4efd-8898-48aa-992b-81bc882dc771",
      "chapter": 13,
      "moduleId": "d0d67a65-b304-4b3d-b6e6-3e1239473a67",
      "moduleSlug": "n4-b13-pengandaian-to-tara",
      "lessonId": "5aa6180f-330d-4b62-93ad-2c719399a4fc",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Vた＋らどうですか",
        "meaning": "Bagaimana kalau …; menyampaikan saran. Nada dan hubungan dengan lawan bicara perlu diperhatikan."
      },
      "after": {
        "pattern": "〜たらどうですか",
        "meaning": "memberi saran — “bagaimana kalau …?”"
      }
    },
    {
      "id": "8f85170b-cb37-4455-993b-7ddb894a850f",
      "chapter": 13,
      "moduleId": "d0d67a65-b304-4b3d-b6e6-3e1239473a67",
      "moduleSlug": "n4-b13-pengandaian-to-tara",
      "lessonId": "5aa6180f-330d-4b62-93ad-2c719399a4fc",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "普通形＋といい（ですね／な） N・Aな非過去肯定：だといい",
        "meaning": "Semoga … / akan baik kalau …; ungkapan harapan atau saran menurut konteks."
      },
      "after": {
        "pattern": "〜といいですね／〜といいな",
        "meaning": "menyatakan harapan atau saran — “semoga … / baik kalau …”"
      }
    },
    {
      "id": "fb8eb9ab-caaf-4d5c-b8f1-8fa10cac8c6d",
      "chapter": 14,
      "moduleId": "e6820110-bef2-47f0-b0c4-4a808d3bf51b",
      "moduleSlug": "n4-b14-pengandaian-ba-nara",
      "lessonId": "e5dd9d4d-e2a5-4806-bc6d-7e4d99123bd9",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "G1 u→e＋ば；G2 る→れば する→すれば；来る→来れば（くれば）",
        "meaning": "Syarat verba. Sertakan Aい→ければ, N／Aな→なら（ば）／であれば, dan negatif→なければ."
      },
      "after": {
        "pattern": "〜ば／〜ければ／〜なら（ば）",
        "meaning": "menyatakan syarat — “jika …”"
      }
    },
    {
      "id": "2c432704-654c-4497-8f53-8a3c0d2bbb17",
      "chapter": 14,
      "moduleId": "e6820110-bef2-47f0-b0c4-4a808d3bf51b",
      "moduleSlug": "n4-b14-pengandaian-ba-nara",
      "lessonId": "e5dd9d4d-e2a5-4806-bc6d-7e4d99123bd9",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "V・Aい普通形／N・Aな-stem＋なら",
        "meaning": "Kalau memang … / kalau tentang …; menanggapi informasi atau asumsi dalam konteks."
      },
      "after": {
        "pattern": "〜なら",
        "meaning": "menanggapi informasi atau asumsi — “kalau memang/tentang …”"
      }
    },
    {
      "id": "c9eb422c-64ee-469a-a942-156365943c33",
      "chapter": 14,
      "moduleId": "e6820110-bef2-47f0-b0c4-4a808d3bf51b",
      "moduleSlug": "n4-b14-pengandaian-ba-nara",
      "lessonId": "8ca72b48-7e11-4495-a097-8b334e1c1fbc",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Vば＋よかった ／ Vなければ＋よかった",
        "meaning": "Seandainya tadi melakukan / tidak melakukan; penyesalan setelah fakta."
      },
      "after": {
        "pattern": "〜ばよかった／〜なければよかった",
        "meaning": "menyatakan penyesalan — “seandainya tadi …”"
      }
    },
    {
      "id": "bcefdff6-4e96-47e3-9de8-06fcb5214a16",
      "chapter": 15,
      "moduleId": "15931cf4-a16b-471c-8b49-8230fddb4b43",
      "moduleSlug": "n4-b15-tujuan-kegunaan-instruksi-tidak-langsung",
      "lessonId": "100f1b0c-2dd6-47cf-8a7a-1fcc90d7c680",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Vます-stem＋に行く／来る／帰る",
        "meaning": "Pergi/datang/pulang untuk melakukan …; fondasi yang belum tercantum eksplisit dalam daftar N5."
      },
      "after": {
        "pattern": "〜に行く／〜に来る／〜に帰る",
        "meaning": "pergi, datang, atau pulang untuk melakukan sesuatu"
      }
    },
    {
      "id": "22faf0ea-231d-4b8f-b3e2-8d22a3f33b14",
      "chapter": 15,
      "moduleId": "15931cf4-a16b-471c-8b49-8230fddb4b43",
      "moduleSlug": "n4-b15-tujuan-kegunaan-instruksi-tidak-langsung",
      "lessonId": "100f1b0c-2dd6-47cf-8a7a-1fcc90d7c680",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Vる＋ために ／ N＋のために",
        "meaning": "Untuk tujuan/manfaat …; fokus tujuan yang disengaja. Fungsi sebab dari ために tidak menjadi target bab ini."
      },
      "after": {
        "pattern": "〜ために／〜のために",
        "meaning": "menyatakan tujuan yang disengaja atau manfaat — “untuk …”"
      }
    },
    {
      "id": "f35204fb-8af8-451a-a41d-28b8ca0c8a76",
      "chapter": 15,
      "moduleId": "15931cf4-a16b-471c-8b49-8230fddb4b43",
      "moduleSlug": "n4-b15-tujuan-kegunaan-instruksi-tidak-langsung",
      "lessonId": "100f1b0c-2dd6-47cf-8a7a-1fcc90d7c680",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Vる／Vない／V可能形＋ように",
        "meaning": "Agar suatu keadaan atau kemampuan terwujud; sering memakai potensial atau negatif."
      },
      "after": {
        "pattern": "〜ように",
        "meaning": "menyatakan tujuan agar suatu keadaan atau kemampuan terwujud"
      }
    },
    {
      "id": "384aada6-16f6-49c9-914d-0861febfb53e",
      "chapter": 15,
      "moduleId": "15931cf4-a16b-471c-8b49-8230fddb4b43",
      "moduleSlug": "n4-b15-tujuan-kegunaan-instruksi-tidak-langsung",
      "lessonId": "015a498e-71e4-4e61-bfa2-60c4cf1dca45",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Vる＋のに＋使う／便利だ／必要だ／時間がかかる",
        "meaning": "Untuk melakukan …, benda berguna/diperlukan atau membutuhkan waktu. Berbeda dari のに “padahal”."
      },
      "after": {
        "pattern": "〜のに使う／便利だ／必要だ／時間がかかる",
        "meaning": "menyatakan kegunaan atau kebutuhan untuk melakukan sesuatu"
      }
    },
    {
      "id": "a9a61b7f-ac7c-4638-9e6e-0b008784ed67",
      "chapter": 15,
      "moduleId": "15931cf4-a16b-471c-8b49-8230fddb4b43",
      "moduleSlug": "n4-b15-tujuan-kegunaan-instruksi-tidak-langsung",
      "lessonId": "015a498e-71e4-4e61-bfa2-60c4cf1dca45",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Vる／Vない＋ように言う",
        "meaning": "Menyampaikan instruksi/permintaan secara tidak langsung; misalnya 早く来るように言いました."
      },
      "after": {
        "pattern": "〜ように言う",
        "meaning": "menyampaikan instruksi atau permintaan secara tidak langsung"
      }
    },
    {
      "id": "7e65dba0-89b1-43a4-99ef-17b99c2eb1f0",
      "chapter": 16,
      "moduleId": "2f6d7bc0-0668-4c19-b52c-0ce627aee300",
      "moduleSlug": "n4-b16-saran-kewajiban-instruksi-tegas",
      "lessonId": "40003450-995c-478d-8478-242827900ce3",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Vた＋ほうがいい ／ Vない＋ほうがいい",
        "meaning": "Lebih baik melakukan / tidak melakukan. Untuk saran spesifik, ajarkan bentuk Vた."
      },
      "after": {
        "pattern": "〜たほうがいい／〜ないほうがいい",
        "meaning": "memberi saran — “lebih baik melakukan/tidak melakukan …”"
      }
    },
    {
      "id": "698d3b5c-41f1-49c4-8768-4f37cbd124b0",
      "chapter": 16,
      "moduleId": "2f6d7bc0-0668-4c19-b52c-0ce627aee300",
      "moduleSlug": "n4-b16-saran-kewajiban-instruksi-tegas",
      "lessonId": "40003450-995c-478d-8478-242827900ce3",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Vなくてはいけない／Vないといけない なくては→なくちゃ；なければ→なきゃ",
        "meaning": "Variasi kewajiban dari konsep yang sudah dikenal. いけない／ならない kadang dilesapkan dalam percakapan."
      },
      "after": {
        "pattern": "〜なくてはいけない／〜ないといけない",
        "meaning": "menyatakan kewajiban — “harus …”"
      }
    },
    {
      "id": "8bcb42e7-bb94-474c-9d1d-33f384a62e58",
      "chapter": 16,
      "moduleId": "2f6d7bc0-0668-4c19-b52c-0ce627aee300",
      "moduleSlug": "n4-b16-saran-kewajiban-instruksi-tegas",
      "lessonId": "40003450-995c-478d-8478-242827900ce3",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Vる＋必要がある／必要はない",
        "meaning": "Perlu/tidak perlu melakukan; bandingkan dengan なくてもいい."
      },
      "after": {
        "pattern": "〜必要がある／〜必要はない",
        "meaning": "menyatakan perlu atau tidak perlu melakukan sesuatu"
      }
    },
    {
      "id": "441eb770-2e1e-4752-b7db-74c7764cdf8c",
      "chapter": 16,
      "moduleId": "2f6d7bc0-0668-4c19-b52c-0ce627aee300",
      "moduleSlug": "n4-b16-saran-kewajiban-instruksi-tegas",
      "lessonId": "d33a978d-d1ba-431a-92e8-4624ee449fca",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Vます-stem＋なさい",
        "meaning": "Instruksi tegas; umum dalam relasi orang tua/guru kepada anak/siswa, bukan permintaan sopan universal."
      },
      "after": {
        "pattern": "〜なさい",
        "meaning": "memberikan instruksi tegas sesuai hubungan pembicara dan pendengar"
      }
    },
    {
      "id": "d5931f00-4b2f-4cd6-984c-4fb7ef5394f2",
      "chapter": 16,
      "moduleId": "2f6d7bc0-0668-4c19-b52c-0ce627aee300",
      "moduleSlug": "n4-b16-saran-kewajiban-instruksi-tegas",
      "lessonId": "d33a978d-d1ba-431a-92e8-4624ee449fca",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "命令形：G1 u→e；G2 る→ろ する→しろ；来る→来い（こい）／Vる＋な",
        "meaning": "Perintah langsung dan larangan tegas “jangan …”. Prioritaskan pemahaman register dan konteks penggunaannya."
      },
      "after": {
        "pattern": "Bentuk perintah（命令形）／〜るな",
        "meaning": "memberi perintah langsung atau larangan tegas — “jangan …”"
      }
    },
    {
      "id": "fdeb6c11-f394-4655-909e-6e3f814c1b21",
      "chapter": 17,
      "moduleId": "4a76eb18-bf1f-4d2b-86bd-fd3a98d3c4a2",
      "moduleSlug": "n4-b17-memberi-menerima-benda",
      "lessonId": "a3e9a81d-f5aa-4af1-84ba-f7e60283ef82",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Pemberiは Penerimaに Bendaを あげる",
        "meaning": "Memberi kepada orang lain dari sudut pandang pemberi."
      },
      "after": {
        "pattern": "〜に〜をあげる",
        "meaning": "memberi benda kepada orang lain"
      }
    },
    {
      "id": "a63c4082-f65c-47b9-a0cc-44afbb00619d",
      "chapter": 17,
      "moduleId": "4a76eb18-bf1f-4d2b-86bd-fd3a98d3c4a2",
      "moduleSlug": "n4-b17-memberi-menerima-benda",
      "lessonId": "a3e9a81d-f5aa-4af1-84ba-f7e60283ef82",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Penerimaは Pemberiに／から Bendaを もらう",
        "meaning": "Menerima dari orang lain; pemilihan に／から bergantung pada pemberi/sumbernya."
      },
      "after": {
        "pattern": "〜に／から〜をもらう",
        "meaning": "menerima benda dari orang lain"
      }
    },
    {
      "id": "35044c6f-f076-4cbe-963d-ffc03a6f5041",
      "chapter": 17,
      "moduleId": "4a76eb18-bf1f-4d2b-86bd-fd3a98d3c4a2",
      "moduleSlug": "n4-b17-memberi-menerima-benda",
      "lessonId": "a3e9a81d-f5aa-4af1-84ba-f7e60283ef82",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Pemberiは 私／kelompok sayaに Bendaを くれる",
        "meaning": "Memberi kepada saya atau pihak yang dipandang dekat dengan saya; konteks menentukan kelompok."
      },
      "after": {
        "pattern": "〜が〜をくれる",
        "meaning": "orang lain memberi benda kepada saya atau pihak saya"
      }
    },
    {
      "id": "cb1e0ca9-29d0-4f54-8432-a8cc0e34e9bd",
      "chapter": 18,
      "moduleId": "778fbd4d-82b0-41b8-bd36-e9f995df9fc3",
      "moduleSlug": "n4-b18-bantuan-permintaan-harapan",
      "lessonId": "f5d34089-ff55-4a51-acda-8d04e6cddc2d",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Pelakuは Penerimaに Vてあげる",
        "meaning": "Melakukan sesuatu untuk orang lain; partikel peran dapat berubah menurut verba."
      },
      "after": {
        "pattern": "〜てあげる",
        "meaning": "melakukan sesuatu untuk orang lain"
      }
    },
    {
      "id": "4e0b4126-767b-40c6-a916-50c40c064dd9",
      "chapter": 18,
      "moduleId": "778fbd4d-82b0-41b8-bd36-e9f995df9fc3",
      "moduleSlug": "n4-b18-bantuan-permintaan-harapan",
      "lessonId": "f5d34089-ff55-4a51-acda-8d04e6cddc2d",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Pelakuは 私／kelompok sayaに Vてくれる",
        "meaning": "Seseorang melakukan sesuatu yang bermanfaat bagi saya/pihak saya."
      },
      "after": {
        "pattern": "〜てくれる",
        "meaning": "orang lain melakukan sesuatu yang bermanfaat bagi saya atau pihak saya"
      }
    },
    {
      "id": "af2ed71a-d82d-4d21-a6ad-34b3e93b21e0",
      "chapter": 18,
      "moduleId": "778fbd4d-82b0-41b8-bd36-e9f995df9fc3",
      "moduleSlug": "n4-b18-bantuan-permintaan-harapan",
      "lessonId": "f5d34089-ff55-4a51-acda-8d04e6cddc2d",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Penerimaは Pelakuに Vてもらう",
        "meaning": "Menerima bantuan atau mengatur agar orang lain melakukan; tidak selalu berarti meminta secara lisan."
      },
      "after": {
        "pattern": "〜てもらう",
        "meaning": "menerima bantuan atau mengatur agar orang lain melakukan sesuatu"
      }
    },
    {
      "id": "a45f36e6-96a1-49ba-8c0e-3e96352e7e7a",
      "chapter": 18,
      "moduleId": "778fbd4d-82b0-41b8-bd36-e9f995df9fc3",
      "moduleSlug": "n4-b18-bantuan-permintaan-harapan",
      "lessonId": "88f32646-5bbe-4791-b8be-af18d2bff13b",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Vてもらえませんか／Vてくれませんか Kasual：てもらえない？／てくれない？",
        "meaning": "Meminta bantuan; gunakan てくれませんか N5 sebagai pembanding, bukan konsep baru seluruhnya."
      },
      "after": {
        "pattern": "〜てもらえませんか／〜てくれませんか",
        "meaning": "meminta bantuan — “bisakah Anda …?”"
      }
    },
    {
      "id": "dec467ae-08fa-47ca-914e-9f9dc8f31863",
      "chapter": 18,
      "moduleId": "778fbd4d-82b0-41b8-bd36-e9f995df9fc3",
      "moduleSlug": "n4-b18-bantuan-permintaan-harapan",
      "lessonId": "88f32646-5bbe-4791-b8be-af18d2bff13b",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Orangに Vてほしい／Vないでほしい",
        "meaning": "Ingin seseorang melakukan / tidak melakukan sesuatu; bedakan dari keinginan diri Vたい."
      },
      "after": {
        "pattern": "〜てほしい／〜ないでほしい",
        "meaning": "menginginkan seseorang melakukan/tidak melakukan sesuatu"
      }
    },
    {
      "id": "e9657f94-fc53-4b0c-a79b-bb8da4c9ff58",
      "chapter": 18,
      "moduleId": "778fbd4d-82b0-41b8-bd36-e9f995df9fc3",
      "moduleSlug": "n4-b18-bantuan-permintaan-harapan",
      "lessonId": "88f32646-5bbe-4791-b8be-af18d2bff13b",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Vてくれてありがとう",
        "meaning": "Berterima kasih atas tindakan orang lain; bentuk hormatnya dibahas setelah keigo."
      },
      "after": {
        "pattern": "〜てくれてありがとう",
        "meaning": "berterima kasih atas tindakan orang lain"
      }
    },
    {
      "id": "f0c421b9-ac27-4129-997e-d424784032a6",
      "chapter": 19,
      "moduleId": "df881aee-7127-4ccf-b8b8-14a14bb2f798",
      "moduleSlug": "n4-b19-pertanyaan-tertanam-pembatasan-jumlah",
      "lessonId": "2959cd36-7a07-4928-b4fb-72b62ab28d6c",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Kata tanya＋普通形＋か、… 普通形＋かどうか、…",
        "meaning": "Pertanyaan tertanam: kapan/di mana … vs apakah … atau tidak. N・Aな nonlampau positif tanpa だ."
      },
      "after": {
        "pattern": "Kata tanya＋〜か／〜かどうか",
        "meaning": "memasukkan pertanyaan ke dalam kalimat — “kapan … / apakah … atau tidak”"
      }
    },
    {
      "id": "a9303260-1760-45bb-b77b-6fec528f73b9",
      "chapter": 19,
      "moduleId": "df881aee-7127-4ccf-b8b8-14a14bb2f798",
      "moduleSlug": "n4-b19-pertanyaan-tertanam-pembatasan-jumlah",
      "lessonId": "2959cd36-7a07-4928-b4fb-72b62ab28d6c",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "N／jumlah＋だけ／しか＋negatif",
        "meaning": "Hanya …; だけ netral, しか menuntut predikat negatif dan sering menekankan keterbatasan."
      },
      "after": {
        "pattern": "〜だけ／〜しか〜ない",
        "meaning": "membatasi jumlah atau cakupan — “hanya …”"
      }
    },
    {
      "id": "5fab0a1a-5b0e-4cda-9bfa-f4659e7516f5",
      "chapter": 19,
      "moduleId": "df881aee-7127-4ccf-b8b8-14a14bb2f798",
      "moduleSlug": "n4-b19-pertanyaan-tertanam-pembatasan-jumlah",
      "lessonId": "2959cd36-7a07-4928-b4fb-72b62ab28d6c",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "N＋ばかり／Vてばかりいる",
        "meaning": "Didominasi oleh … / terus melakukan itu saja. Berbeda dari Vたばかり pada Bab 8."
      },
      "after": {
        "pattern": "〜ばかり／〜てばかりいる",
        "meaning": "menyatakan sesuatu didominasi hal atau kegiatan yang sama"
      }
    },
    {
      "id": "525f3286-15cd-49fa-898e-1b35a7240b62",
      "chapter": 19,
      "moduleId": "df881aee-7127-4ccf-b8b8-14a14bb2f798",
      "moduleSlug": "n4-b19-pertanyaan-tertanam-pembatasan-jumlah",
      "lessonId": "ea68db2b-380e-415f-a706-76180d7b0ca8",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "N／Vる＋だけで",
        "meaning": "Cukup/hanya dengan …; menunjukkan syarat atau sarana yang minimal."
      },
      "after": {
        "pattern": "〜だけで",
        "meaning": "menyatakan syarat atau sarana minimal — “cukup/hanya dengan …”"
      }
    },
    {
      "id": "3dba7a3c-ffbd-49bf-b0e6-fb84fdbe0317",
      "chapter": 19,
      "moduleId": "df881aee-7127-4ccf-b8b8-14a14bb2f798",
      "moduleSlug": "n4-b19-pertanyaan-tertanam-pembatasan-jumlah",
      "lessonId": "ea68db2b-380e-415f-a706-76180d7b0ca8",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "N＋だけでなく、Nも…",
        "meaning": "Bukan hanya A, B juga; perluasan pada klausa diajarkan setelah bentuk sambungan dipahami."
      },
      "after": {
        "pattern": "〜だけでなく、〜も",
        "meaning": "menambahkan informasi — “bukan hanya …, tetapi … juga”"
      }
    },
    {
      "id": "40677b8e-a5a8-4193-9d29-c775b8184068",
      "chapter": 19,
      "moduleId": "df881aee-7127-4ccf-b8b8-14a14bb2f798",
      "moduleSlug": "n4-b19-pertanyaan-tertanam-pembatasan-jumlah",
      "lessonId": "ea68db2b-380e-415f-a706-76180d7b0ca8",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Jumlah＋も／は",
        "meaning": "Penekanan jumlah yang terasa banyak atau batas minimal, sesuai konteks."
      },
      "after": {
        "pattern": "Jumlah＋も／Jumlah＋は",
        "meaning": "menekankan jumlah yang terasa banyak atau batas minimal"
      }
    },
    {
      "id": "b391824a-4944-467a-ada3-935d375e7ab5",
      "chapter": 20,
      "moduleId": "3dd4992b-a41c-4588-92ac-b6373b73d03b",
      "moduleSlug": "n4-b20-perbandingan-batas-kondisi",
      "lessonId": "12710081-1e60-410d-baf5-ecc973daa3cb",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "AはBほど〜ない／N・V普通形＋ほど",
        "meaning": "Tidak se-… B / sampai tingkat …; jelaskan fungsi perbandingan dan derajat dengan konteks berbeda."
      },
      "after": {
        "pattern": "〜ほど〜ない／〜ほど",
        "meaning": "menyatakan perbandingan negatif atau derajat — “tidak se-… / sampai …”"
      }
    },
    {
      "id": "b95dda50-4227-4e68-828e-66b240899ea2",
      "chapter": 20,
      "moduleId": "3dd4992b-a41c-4588-92ac-b6373b73d03b",
      "moduleSlug": "n4-b20-perbandingan-batas-kondisi",
      "lessonId": "12710081-1e60-410d-baf5-ecc973daa3cb",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Jumlah＋くらい／ぐらい／Waktu＋ごろ",
        "meaning": "Sekitar jumlah/durasi vs sekitar titik waktu. Perluasan くらい untuk derajat disertakan sebagai variasi."
      },
      "after": {
        "pattern": "〜くらい／〜ぐらい／〜ごろ",
        "meaning": "menyatakan perkiraan jumlah, durasi, atau titik waktu"
      }
    },
    {
      "id": "125510ff-57cc-426c-b80e-fad4bd67a2b3",
      "chapter": 20,
      "moduleId": "3dd4992b-a41c-4588-92ac-b6373b73d03b",
      "moduleSlug": "n4-b20-perbandingan-batas-kondisi",
      "lessonId": "12710081-1e60-410d-baf5-ecc973daa3cb",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Periodeに＋jumlah回／N・jumlah＋ごとに",
        "meaning": "Frekuensi per periode dan pengulangan setiap unit; misalnya 一週間に三回、一時間ごとに."
      },
      "after": {
        "pattern": "〜に〜回／〜ごとに",
        "meaning": "menyatakan frekuensi per periode atau pengulangan setiap unit"
      }
    },
    {
      "id": "f0c253a0-ee38-491f-a957-c24ea0e1fa94",
      "chapter": 20,
      "moduleId": "3dd4992b-a41c-4588-92ac-b6373b73d03b",
      "moduleSlug": "n4-b20-perbandingan-batas-kondisi",
      "lessonId": "12710081-1e60-410d-baf5-ecc973daa3cb",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Jumlah＋以上／以下／未満；N＋以外",
        "meaning": "以上／以下 termasuk batas; 未満 di bawah batas tanpa menyertakannya; 以外 berarti selain."
      },
      "after": {
        "pattern": "〜以上／〜以下／〜未満／〜以外",
        "meaning": "menyatakan batas jumlah atau pengecualian — “selain …”"
      }
    },
    {
      "id": "b9365e25-6149-4998-9481-8bcaf30c3809",
      "chapter": 20,
      "moduleId": "3dd4992b-a41c-4588-92ac-b6373b73d03b",
      "moduleSlug": "n4-b20-perbandingan-batas-kondisi",
      "lessonId": "e2881a0d-ee3f-4700-86b1-ccef2951ec44",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "V・Aい普通形／Aな＋な／N＋の＋場合（は）",
        "meaning": "Dalam hal/jika terjadi …; sering untuk petunjuk atau prosedur."
      },
      "after": {
        "pattern": "〜場合（は）",
        "meaning": "menyatakan keadaan bersyarat — “dalam hal/jika terjadi …”"
      }
    },
    {
      "id": "31347e0b-b65f-4dec-81bd-48514de1a04a",
      "chapter": 20,
      "moduleId": "3dd4992b-a41c-4588-92ac-b6373b73d03b",
      "moduleSlug": "n4-b20-perbandingan-batas-kondisi",
      "lessonId": "e2881a0d-ee3f-4700-86b1-ccef2951ec44",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Vた／Vない＋まま Aい／Aな＋な／N＋の＋まま",
        "meaning": "Tetap dalam keadaan …; keadaan tidak berubah sementara hal lain terjadi."
      },
      "after": {
        "pattern": "〜まま",
        "meaning": "menyatakan keadaan yang tetap atau tidak berubah"
      }
    },
    {
      "id": "9b1195b6-a59c-467e-8c45-0e6480dc196c",
      "chapter": 20,
      "moduleId": "3dd4992b-a41c-4588-92ac-b6373b73d03b",
      "moduleSlug": "n4-b20-perbandingan-batas-kondisi",
      "lessonId": "e2881a0d-ee3f-4700-86b1-ccef2951ec44",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Vる／Vた＋とおりに N＋のとおりに／N＋どおりに",
        "meaning": "Sesuai/seperti petunjuk atau acuan: 説明したとおりに、予定どおりに."
      },
      "after": {
        "pattern": "〜とおりに／〜どおりに",
        "meaning": "melakukan sesuatu sesuai petunjuk atau acuan"
      }
    },
    {
      "id": "6fc52ebb-2d7c-4da6-8263-3cc27d7c2b6d",
      "chapter": 21,
      "moduleId": "bc0d9617-17b7-4293-8250-542ac9dfdf45",
      "moduleSlug": "n4-b21-kalimat-pasif",
      "lessonId": "4048438e-6d2e-4322-90fd-b2859e70dada",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "受身形：G1 u→a＋れる（う→われる） G2 る→られる；する→される；来る→来られる",
        "meaning": "Konjugasi pasif: 書かれる、買われる、食べられる. Bedakan potensial melalui struktur dan konteks."
      },
      "after": {
        "pattern": "Bentuk pasif（受身形）",
        "meaning": "membentuk kata kerja pasif — “dikenai suatu tindakan”"
      }
    },
    {
      "id": "72b03ce1-80bd-4b30-b23c-582fa5efab75",
      "chapter": 21,
      "moduleId": "bc0d9617-17b7-4293-8250-542ac9dfdf45",
      "moduleSlug": "n4-b21-kalimat-pasif",
      "lessonId": "4048438e-6d2e-4322-90fd-b2859e70dada",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Penerimaは Pelakuに V受身",
        "meaning": "Pasif langsung: 私は先生に褒められました."
      },
      "after": {
        "pattern": "〜は〜に＋V pasif",
        "meaning": "menyatakan tindakan yang diterima subjek dari pelaku"
      }
    },
    {
      "id": "b0f52855-f571-478f-a932-33b52781c2ab",
      "chapter": 21,
      "moduleId": "bc0d9617-17b7-4293-8250-542ac9dfdf45",
      "moduleSlug": "n4-b21-kalimat-pasif",
      "lessonId": "755f4715-42e0-4087-b796-b00da9540fb6",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Pihak terdampakは Pelakuに Nを V受身",
        "meaning": "Pasif yang melibatkan milik/bagian tubuh: 私は弟にケーキを食べられました."
      },
      "after": {
        "pattern": "〜は〜に〜を＋V pasif",
        "meaning": "menyatakan tindakan pada milik atau bagian tubuh yang memengaruhi subjek"
      }
    },
    {
      "id": "14c1e4cb-db33-44d3-8a4a-806f63b9e27f",
      "chapter": 21,
      "moduleId": "bc0d9617-17b7-4293-8250-542ac9dfdf45",
      "moduleSlug": "n4-b21-kalimat-pasif",
      "lessonId": "755f4715-42e0-4087-b796-b00da9540fb6",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Pihak terdampakは Pelaku／kejadianに V受身",
        "meaning": "Pasif tidak langsung, termasuk verba intransitif: 雨に降られました."
      },
      "after": {
        "pattern": "〜に＋V pasif（dampak tidak langsung）",
        "meaning": "menyatakan bahwa subjek terdampak suatu tindakan atau kejadian"
      }
    },
    {
      "id": "c74b4109-ff85-463c-8ef3-801d0a5b8555",
      "chapter": 21,
      "moduleId": "bc0d9617-17b7-4293-8250-542ac9dfdf45",
      "moduleSlug": "n4-b21-kalimat-pasif",
      "lessonId": "755f4715-42e0-4087-b796-b00da9540fb6",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Nは V受身 ／ Nは Pelakuによって V受身",
        "meaning": "Benda/peristiwa sebagai topik; によって untuk pelaku dalam konteks tertentu, misalnya penciptaan."
      },
      "after": {
        "pattern": "〜は＋V pasif／〜によって＋V pasif",
        "meaning": "menjelaskan benda atau peristiwa dengan bentuk pasif"
      }
    },
    {
      "id": "048f2898-cc0e-4cf4-be16-d18a94db71c7",
      "chapter": 22,
      "moduleId": "dec559f0-9e4f-44e2-b89d-e66df1a5525d",
      "moduleSlug": "n4-b22-kausatif-kausatif-pasif",
      "lessonId": "481962f1-b0ec-4fd8-8881-cfad7df3bde0",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "使役形：G1 u→a＋せる（う→わせる） G2 る→させる；する→させる；来る→来させる",
        "meaning": "Konjugasi kausatif: 書かせる、買わせる、食べさせる、 来させる（こさせる）."
      },
      "after": {
        "pattern": "Bentuk kausatif（使役形）",
        "meaning": "membentuk kata kerja untuk menyuruh atau mengizinkan tindakan"
      }
    },
    {
      "id": "04b312f4-1eda-4463-be08-ea3a506b12a2",
      "chapter": 22,
      "moduleId": "dec559f0-9e4f-44e2-b89d-e66df1a5525d",
      "moduleSlug": "n4-b22-kausatif-kausatif-pasif",
      "lessonId": "481962f1-b0ec-4fd8-8881-cfad7df3bde0",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "Penyebabは Pelakuに Bendaを V使役 Intransitif：Penyebabは Pelakuを／に V使役",
        "meaning": "Kausatif transitif dan intransitif. Makna menyuruh atau mengizinkan ditentukan konteks, bukan dua rumus terpisah."
      },
      "after": {
        "pattern": "〜に〜を＋V kausatif／〜を・に＋V kausatif",
        "meaning": "menyatakan siapa yang disuruh atau diizinkan melakukan sesuatu"
      }
    },
    {
      "id": "d15fef58-d4b8-4447-a4da-0bb330b3350a",
      "chapter": 22,
      "moduleId": "dec559f0-9e4f-44e2-b89d-e66df1a5525d",
      "moduleSlug": "n4-b22-kausatif-kausatif-pasif",
      "lessonId": "481962f1-b0ec-4fd8-8881-cfad7df3bde0",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "V使役＋てください V使役＋てあげる／てくれる／てもらう",
        "meaning": "Meminta izin atau memberi/menerima kesempatan melakukan; bertumpu pada bab pemberian tindakan."
      },
      "after": {
        "pattern": "V kausatifて＋ください／あげる／くれる／もらう",
        "meaning": "meminta izin atau memberi dan menerima kesempatan melakukan sesuatu"
      }
    },
    {
      "id": "1bd12c89-d0c9-48c8-8f9b-50c0499f68af",
      "chapter": 22,
      "moduleId": "dec559f0-9e4f-44e2-b89d-e66df1a5525d",
      "moduleSlug": "n4-b22-kausatif-kausatif-pasif",
      "lessonId": "7160069b-1114-4338-b594-60464920e7d6",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "V使役 → hapus る＋られる G1：書かせられる；G2：食べさせられる",
        "meaning": "Konjugasi kausatif-pasif. Tidak beraturan: する→させられる、来る→来させられる."
      },
      "after": {
        "pattern": "Bentuk kausatif-pasif（使役受身形）",
        "meaning": "membentuk kata kerja untuk tindakan yang dipaksakan kepada pelaku"
      }
    },
    {
      "id": "e27a8964-c6ba-4fba-8c0b-505a79ae5b58",
      "chapter": 22,
      "moduleId": "dec559f0-9e4f-44e2-b89d-e66df1a5525d",
      "moduleSlug": "n4-b22-kausatif-kausatif-pasif",
      "lessonId": "7160069b-1114-4338-b594-60464920e7d6",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Pelaku terpaksaは Penyuruhに V使役受身",
        "meaning": "Terpaksa/disuruh melakukan …; 私は先生に作文を書かせられました."
      },
      "after": {
        "pattern": "〜は〜に＋V kausatif-pasif",
        "meaning": "menyatakan terpaksa atau disuruh melakukan sesuatu"
      }
    },
    {
      "id": "4442b73f-f698-41f5-97b1-9c0a22b4f06a",
      "chapter": 22,
      "moduleId": "dec559f0-9e4f-44e2-b89d-e66df1a5525d",
      "moduleSlug": "n4-b22-kausatif-kausatif-pasif",
      "lessonId": "7160069b-1114-4338-b594-60464920e7d6",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "G1 a＋せられる → a＋される 書かせられる→書かされる",
        "meaning": "Bentuk pendek yang umum; jangan terapkan pada verba berakhiran す: 話させられる tetap."
      },
      "after": {
        "pattern": "〜せられる／〜される（bentuk pendek）",
        "meaning": "memendekkan bentuk kausatif-pasif pada verba Golongan 1 tertentu"
      }
    },
    {
      "id": "4d327a80-19df-4383-9ecf-c2819ee2b9a1",
      "chapter": 23,
      "moduleId": "75f7e5ca-c982-4011-9803-7910b6b91002",
      "moduleSlug": "n4-b23-bahasa-hormat-sonkeigo",
      "lessonId": "cd4149b3-0b27-41d5-adbf-bdd0a69b6f8e",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "お＋Vます-stem＋になる ご＋nomina verbal＋になる（jika sesuai）",
        "meaning": "Pola hormat untuk verba yang menerima bentuk ini. Tidak semua verba dapat dibentuk secara mekanis."
      },
      "after": {
        "pattern": "お〜になる／ご〜になる",
        "meaning": "menghormati tindakan orang yang dibicarakan"
      }
    },
    {
      "id": "25c228b0-1f32-485f-b270-3b3f0ed8ba96",
      "chapter": 23,
      "moduleId": "75f7e5ca-c982-4011-9803-7910b6b91002",
      "moduleSlug": "n4-b23-bahasa-hormat-sonkeigo",
      "lessonId": "cd4149b3-0b27-41d5-adbf-bdd0a69b6f8e",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "V受身形 untuk makna hormat",
        "meaning": "Bentuk 〜れる／られる yang menghormati pelaku, bukan berarti pelaku dikenai tindakan."
      },
      "after": {
        "pattern": "〜れる／〜られる（hormat）",
        "meaning": "menggunakan bentuk serupa pasif untuk menghormati pelaku"
      }
    },
    {
      "id": "4ff7d528-056e-456a-b117-02174d3000ce",
      "chapter": 23,
      "moduleId": "75f7e5ca-c982-4011-9803-7910b6b91002",
      "moduleSlug": "n4-b23-bahasa-hormat-sonkeigo",
      "lessonId": "be48a5d3-e8fe-479c-badf-f31e30a769f0",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "行く・来る・いる→いらっしゃる 食べる・飲む→召し上がる；見る→ご覧になる",
        "meaning": "Kelompok verba hormat khusus; pelajari sebagai pasangan bentuk biasa dan hormat."
      },
      "after": {
        "pattern": "いらっしゃる／召し上がる／ご覧になる",
        "meaning": "menghormati kegiatan pergi, datang, berada, makan, minum, dan melihat"
      }
    },
    {
      "id": "c13c7fe2-d336-44f0-ac28-b4434a75d74a",
      "chapter": 23,
      "moduleId": "75f7e5ca-c982-4011-9803-7910b6b91002",
      "moduleSlug": "n4-b23-bahasa-hormat-sonkeigo",
      "lessonId": "be48a5d3-e8fe-479c-badf-f31e30a769f0",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "する→なさる；言う→おっしゃる 知っている→ご存じだ",
        "meaning": "Verba/ungkapan hormat khusus lainnya; ご存じだ bukan konjugasi pasif."
      },
      "after": {
        "pattern": "なさる／おっしゃる／ご存じだ",
        "meaning": "menghormati kegiatan melakukan, mengatakan, dan mengetahui"
      }
    },
    {
      "id": "c70802a3-abea-4002-a6f7-27123b74f27b",
      "chapter": 23,
      "moduleId": "75f7e5ca-c982-4011-9803-7910b6b91002",
      "moduleSlug": "n4-b23-bahasa-hormat-sonkeigo",
      "lessonId": "be48a5d3-e8fe-479c-badf-f31e30a769f0",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "いらっしゃいます・なさいます・おっしゃいます お＋Vます-stem＋ください／ご＋N＋ください",
        "meaning": "Konjugasi sopan khusus dan instruksi hormat; hubungkan kembali お待ちください dari N5."
      },
      "after": {
        "pattern": "いらっしゃいます・お〜ください／ご〜ください",
        "meaning": "menggunakan bentuk sopan khusus dan menyampaikan instruksi hormat"
      }
    },
    {
      "id": "f0bb035c-2a94-4e0b-b943-e97fb4057610",
      "chapter": 24,
      "moduleId": "6bce9509-443d-4932-85c4-b500d6ab2d5a",
      "moduleSlug": "n4-b24-bahasa-merendah-permintaan-formal",
      "lessonId": "5368a7ce-fb1a-48cd-a138-c6d99938411e",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "お＋Vます-stem＋する／いたす ご＋nomina verbal＋する／いたす（jika sesuai）",
        "meaning": "Pola merendah, misalnya お持ちする、ご案内する. Pilih verba dan arah tindakan yang sesuai."
      },
      "after": {
        "pattern": "お〜する／お〜いたす・ご〜する／ご〜いたす",
        "meaning": "merendahkan tindakan diri atau pihak sendiri untuk menghormati pihak lain"
      }
    },
    {
      "id": "a4fc5755-2cf0-4611-be9a-cd295f6f44fc",
      "chapter": 24,
      "moduleId": "6bce9509-443d-4932-85c4-b500d6ab2d5a",
      "moduleSlug": "n4-b24-bahasa-merendah-permintaan-formal",
      "lessonId": "5368a7ce-fb1a-48cd-a138-c6d99938411e",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "参る・申す・いたす・おる 伺う・拝見する・お目にかかる・存じている",
        "meaning": "Verba merendah/sangat sopan; arti dan pasangan bentuk biasa tersedia di tabel khusus lampiran."
      },
      "after": {
        "pattern": "参る／申す／いたす・伺う／拝見する",
        "meaning": "menggunakan ungkapan khusus yang merendah atau sangat sopan"
      }
    },
    {
      "id": "67669ac0-c0f3-48a3-9ffe-50d8eec3fae7",
      "chapter": 24,
      "moduleId": "6bce9509-443d-4932-85c4-b500d6ab2d5a",
      "moduleSlug": "n4-b24-bahasa-merendah-permintaan-formal",
      "lessonId": "5368a7ce-fb1a-48cd-a138-c6d99938411e",
      "lessonSlug": "tata-bahasa-1",
      "before": {
        "pattern": "ある→ございます ／ です→でございます",
        "meaning": "Bahasa sopan (丁寧語); tidak otomatis berarti kenjougo atau perubahan keadaan."
      },
      "after": {
        "pattern": "ございます／でございます",
        "meaning": "menyatakan keberadaan atau identitas dengan sangat sopan"
      }
    },
    {
      "id": "7464741d-e555-41d3-9740-20a42e367d4f",
      "chapter": 24,
      "moduleId": "6bce9509-443d-4932-85c4-b500d6ab2d5a",
      "moduleSlug": "n4-b24-bahasa-merendah-permintaan-formal",
      "lessonId": "13c9f205-cab0-460f-b237-74284b18416a",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "あげる→差し上げる；もらう→いただく くれる→くださる（くださいます）",
        "meaning": "Bentuk memberi-menerima yang merendah atau menghormati; perhatikan siapa pemberi/penerima."
      },
      "after": {
        "pattern": "差し上げる／いただく／くださる",
        "meaning": "memberi atau menerima benda dengan bahasa merendah atau hormat"
      }
    },
    {
      "id": "a7d157a1-a976-4101-99ae-0c3976bbc0f0",
      "chapter": 24,
      "moduleId": "6bce9509-443d-4932-85c4-b500d6ab2d5a",
      "moduleSlug": "n4-b24-bahasa-merendah-permintaan-formal",
      "lessonId": "13c9f205-cab0-460f-b237-74284b18416a",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Vて差し上げる／Vていただく／Vてくださる Vていただけませんか／Vていただけますか",
        "meaning": "Pemberian tindakan secara hormat/merendah dan permintaan bantuan; bandingkan dengan てもらえませんか."
      },
      "after": {
        "pattern": "〜て差し上げる／〜ていただく／〜てくださる",
        "meaning": "memberi atau menerima bantuan serta meminta bantuan dengan hormat"
      }
    },
    {
      "id": "90ed9f69-9235-4d85-ad1e-e30e615d3e39",
      "chapter": 24,
      "moduleId": "6bce9509-443d-4932-85c4-b500d6ab2d5a",
      "moduleSlug": "n4-b24-bahasa-merendah-permintaan-formal",
      "lessonId": "13c9f205-cab0-460f-b237-74284b18416a",
      "lessonSlug": "tata-bahasa-2",
      "before": {
        "pattern": "Vていただき、ありがとうございます Vてくださって、ありがとうございます",
        "meaning": "Terima kasih atas tindakan orang lain, dengan perbedaan sudut pandang menerima/menghormati."
      },
      "after": {
        "pattern": "〜ていただき／〜てくださって、ありがとうございます",
        "meaning": "berterima kasih atas tindakan orang lain dengan bahasa formal"
      }
    }
  ]
}$plan$::jsonb;
  r jsonb; actual jsonb; completed int;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtext('curriculum-boundary:graph'));
  PERFORM pg_advisory_xact_lock(hashtext('curriculum-boundary:' || (p->>'courseId')));
  SELECT count(*) INTO completed FROM n4_pattern_format_backup_193 WHERE course_id=(p->>'courseId')::uuid;
  IF completed = jsonb_array_length(p->'rows') THEN RETURN; END IF;
  IF completed <> 0 THEN RAISE EXCEPTION '193 incomplete backup; review before applying'; END IF;
  LOCK TABLE courses, modules, lessons, module_grammar IN SHARE ROW EXCLUSIVE MODE;
  IF NOT EXISTS (SELECT 1 FROM courses WHERE id=(p->>'courseId')::uuid AND slug='n4') THEN
    RAISE EXCEPTION '193 N4 course changed';
  END IF;
  -- Validate all rows before writing any. A teacher edit is never overwritten.
  FOR r IN SELECT value FROM jsonb_array_elements(p->'rows') LOOP
    SELECT jsonb_build_object('pattern',g.pattern,'meaning',g.meaning) INTO actual
      FROM module_grammar g JOIN modules m ON m.id=g.module_id JOIN lessons l ON l.id=g.lesson_id
      WHERE g.id=(r->>'id')::uuid AND m.id=(r->>'moduleId')::uuid
        AND m.course_id=(p->>'courseId')::uuid AND m.slug=r->>'moduleSlug'
        AND l.id=(r->>'lessonId')::uuid AND l.module_id=m.id AND l.slug=r->>'lessonSlug';
    IF actual IS NULL OR (actual IS DISTINCT FROM r->'before' AND actual IS DISTINCT FROM r->'after') THEN
      RAISE EXCEPTION '193 N4 card changed or missing: %',r->>'id';
    END IF;
  END LOOP;
  FOR r IN SELECT value FROM jsonb_array_elements(p->'rows') LOOP
    INSERT INTO n4_pattern_format_backup_193(grammar_id,course_id,before_fields,after_fields)
      SELECT g.id,(p->>'courseId')::uuid,jsonb_build_object('pattern',g.pattern,'meaning',g.meaning),r->'after'
      FROM module_grammar g WHERE g.id=(r->>'id')::uuid;
    UPDATE module_grammar SET pattern=r->'after'->>'pattern',meaning=r->'after'->>'meaning',updated_at=now()
      WHERE id=(r->>'id')::uuid
        AND (pattern IS DISTINCT FROM r->'after'->>'pattern' OR meaning IS DISTINCT FROM r->'after'->>'meaning');
  END LOOP;
END $format$;
