const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\'':'&#39;'}[c]));
const options=(items,selected='')=>Object.entries(items).map(([value,label])=>`<option value="${esc(value)}"${value===String(selected??'')?' selected':''}>${esc(label)}</option>`).join('');
const labels={referral:'Referral',instagram:'Instagram',tiktok:'TikTok',whatsapp:'WhatsApp',website:'Website',event:'Acara',other:'Lainnya',cost:'Biaya',career:'Jalur kerja',convenience:'Fleksibilitas',language:'Bahasa',jobs:'Akses kerja',time:'Waktu',trust:'Kepercayaan',ex_intern_hospitality:'Eks-intern hospitality',ex_intern_other:'Eks-intern lainnya',fresh_graduate:'Lulusan baru',worker:'Sedang bekerja',cheap:'Murah',reasonable:'Masuk akal',somewhat_expensive:'Agak mahal',expensive:'Mahal',not_relevant:'Bukan pertimbangan utama',unrecorded:'Belum dicatat'};
const money=value=>{try{return 'Rp'+BigInt(value??0).toLocaleString('id-ID');}catch{return '—';}};
const pct=(a,b)=>b?`${Math.round(100*a/b)}%`:'—';
const monday=()=>{const d=new Date();d.setUTCHours(0,0,0,0);d.setUTCDate(d.getUTCDate()-(d.getUTCDay()+6)%7-7);return d.toISOString().slice(0,10);};
const controlLabels=root=>root.querySelectorAll('label').forEach(label=>{const field=label.querySelector('input,select,textarea');if(field)field.setAttribute('aria-label',label.firstChild.textContent.trim());});
function table(title,rows){return `<section class="growth-panel"><h3>${esc(title)}</h3>${rows.length?`<div class="growth-table"><table><thead><tr><th>Kategori</th><th>Lead</th><th>Kualifikasi</th><th>Bayar</th><th>Lead → bayar</th></tr></thead><tbody>${rows.map(row=>`<tr><td>${esc(labels[row.label]||row.label)}</td><td>${Number(row.leads)}</td><td>${Number(row.qualified)}</td><td>${Number(row.paid)}</td><td>${pct(Number(row.paid),Number(row.leads))}</td></tr>`).join('')}</tbody></table></div>`:'<p>Belum ada data minggu ini.</p>'}</section>`;}

export function createMarketingGrowth({root,api,access,courses,onOpen}){
  if(!document.querySelector('link[data-growth-style]')){const link=document.createElement('link');link.rel='stylesheet';link.href='styles/marketing-growth.css?v=20261003';link.dataset.growthStyle='true';document.head.append(link);}
  const node=document.createElement('section');node.id='marketing-growth';node.hidden=true;root.append(node);
  const global=access.isAdmin||access.scopes?.marketing==='global',available=global?courses:courses.filter(c=>access.scopes?.marketing?.includes(c.id));
  const courseOptions={...(global?{'':'Semua kursus'}:{}),...Object.fromEntries(available.map(c=>[c.id,c.title]))};
  let active=false,loading=0,report=null,dirty=false,busy=false,activeCourse=global?'':available[0]?.id||'',activeWeek=monday();
  node.innerHTML=`<header class="growth-heading"><div><p class="growth-eyebrow">MARKETING / GROWTH REVIEW</p><h1>Temukan yang benar-benar bekerja.</h1><p>Bandingkan calon siswa, pembelian terverifikasi, dan kata-kata pelanggan per minggu.</p></div></header>
    <form id="growth-filter" class="growth-filter"><label>Kursus<select name="courseId">${options(courseOptions,activeCourse)}</select></label><label>Minggu dimulai (Senin)<input name="week" type="date" value="${activeWeek}" required></label><button type="submit">Tampilkan</button></form>
    <p id="growth-notice" role="status" aria-live="polite"></p><div id="growth-content"></div>
    <details class="growth-guide"><summary>Panduan validasi 30 hari & wawancara</summary><div class="growth-guide-grid"><section><h3>Ritme 30 hari</h3><ol><li>Minggu 1: 15–20 wawancara; catat problem, bahasa pelanggan, dan alternatif.</li><li>Minggu 2: uji penawaran dan reaksi harga setelah memahami kebutuhan.</li><li>Minggu 3: bandingkan pesan Cost, Career, Convenience; ubah satu variabel utama.</li><li>Minggu 4: bandingkan kualitas referral, organik, dan outreach lalu pilih langkah berikutnya.</li></ol></section><section><h3>Panduan wawancara</h3><ol><li>Jalur apa yang sudah dicari untuk berangkat/kembali ke Jepang?</li><li>Apa bagian tersulit? Program lain apa yang dibandingkan?</li><li>Bantuan apa yang paling dibutuhkan saat ini?</li><li>Seberapa jauh kemampuan bahasa Jepang sekarang?</li><li>Apa yang menarik atau tidak dari program online?</li><li>Sebelum melihat harga kami, berapa yang terasa masuk akal?</li><li>Sesudah melihat penawaran, apa alasan mengambil atau tidak mengambilnya?</li></ol></section></div></details>`;
  const $=name=>node.querySelector('#growth-'+name);controlLabels(node);
  const message=e=>({crm_version_conflict:'Data sudah diperbarui anggota lain. Salin isianmu lalu muat ulang.',crm_scope_required:'Akses Marketing untuk kursus ini tidak tersedia.',crm_invalid_week:'Pilih tanggal Senin untuk awal minggu.',crm_experiment_hypothesis_required:'Isi hipotesis untuk eksperimen utama.',crm_experiment_result_required:'Catat hasil sebelum menandai eksperimen selesai.',crm_experiment_owner_scope:'PIC eksperimen harus memiliki akses Marketing pada kursus ini.',crm_invalid_spend:'Periksa sumber dan jumlah biaya.'})[e.message]||'Data belum dapat dimuat atau disimpan. Coba lagi.';
  function canLeave(){if(busy){$('notice').textContent='Tunggu sampai penyimpanan selesai.';return false;}return !dirty||confirm('Isian Growth Review belum disimpan. Tinggalkan perubahan?');}
  async function load(){
    const ticket=++loading;$('notice').textContent='Memuat review…';$('content').innerHTML='';
    try{const query=new URLSearchParams({week:activeWeek,...(activeCourse?{courseId:activeCourse}:{})});const data=await api('/crm/growth?'+query);if(ticket!==loading||!active)return;
      report=data;dirty=false;render();$('notice').textContent='';
    }catch(e){if(ticket!==loading||!active)return;$('notice').textContent=message(e);$('content').innerHTML='<button type="button" id="growth-retry">Coba lagi</button>';$('retry').onclick=load;}
  }
  function render(){
    const d=report,s=d.summary,spendTotal=d.spend.reduce((sum,r)=>sum+BigInt(r.amount_idr),0n),hasSpend=d.spend.length>0;
    const periodCac=hasSpend&&Number(s.period_paid)>0?money(spendTotal/BigInt(s.period_paid)):'—';
    const review=d.review||{},kpis=[['Lead baru',s.leads],['Terkualifikasi',s.qualified],['Wawancara',s.interviews],['Konsultasi',s.consulted],['Diberi penawaran',s.offered],['Bayar dari lead baru',s.cohort_paid],['Bayar minggu ini',s.period_paid]];
    const evidenceNotice=`${Number(s.unverified_deals)} deal yang dicatat belum terhubung ke pesanan. Angka bayar mencocokkan email dan kursus lead dengan pesanan disetujui yang dibuat sejak lead dicatat; penjualan lewat nomor WhatsApp saja belum terhitung.`;
    $('content').innerHTML=`<div class="growth-stats">${kpis.map(([label,value])=>`<article><span>${label}</span><strong>${Number(value)||0}</strong></article>`).join('')}</div>
      <section class="growth-panel"><h2>Funnel dan ekonomi</h2><div class="growth-metrics"><div><span>Lead → bayar</span><strong>${pct(s.cohort_paid,s.leads)}</strong></div><div><span>Kualifikasi → bayar</span><strong>${pct(s.qualified_paid,s.qualified)}</strong></div><div><span>Pendapatan terhubung minggu ini</span><strong>${money(s.period_revenue_idr)}</strong></div><div><span>Biaya per siswa berbayar</span><strong>${periodCac}</strong></div></div><p>Konversi memakai lead yang masuk pada minggu terpilih; pembayaran mereka dapat terjadi setelah minggu itu. Pendapatan dan biaya per siswa memakai pembayaran serta biaya yang dicatat untuk minggu terpilih. Biaya per siswa hanya muncul jika biaya sudah dicatat dan ada pembelian terverifikasi.</p><p>${esc(evidenceNotice)}</p>${Number(s.leads)<20?'<p class="growth-caution">Sampel lead masih kecil. Gunakan untuk belajar, belum untuk memutuskan scale iklan.</p>':''}</section>
      <div class="growth-grid">${table('Sumber calon siswa',d.sources)}${table('Pesan Cost / Career / Convenience',d.angles)}${table('Latar belakang',d.backgrounds)}${table('Masalah utama',d.problems)}${table('Reaksi harga',d.priceReactions)}${table('Orang yang mereferensikan',d.referrers)}</div>
      <div class="growth-grid"><section class="growth-panel"><h3>Keberatan yang tercatat</h3>${d.objections.length?`<ol>${d.objections.map(o=>`<li>${esc(o.label)} <small>(${Number(o.leads)})</small></li>`).join('')}</ol>`:'<p>Belum ada keberatan yang dicatat.</p>'}</section><section class="growth-panel"><h3>Kata-kata pelanggan</h3>${d.customerWords.length?`<ul>${d.customerWords.map(q=>`<li>“${esc(q)}”</li>`).join('')}</ul>`:'<p>Belum ada kutipan wawancara.</p>'}</section></div>
      <section class="growth-panel"><h2>Biaya akuisisi minggu ini</h2><p>Catat biaya nyata per sumber untuk minggu dan cakupan kursus ini. Jangan masukkan biaya yang sama dua kali pada cakupan semua kursus dan kursus tertentu.</p><div class="growth-table"><table><thead><tr><th>Sumber</th><th>Biaya</th><th>Catatan</th></tr></thead><tbody>${d.spend.map(r=>`<tr><td>${esc(labels[r.source])}</td><td>${money(r.amount_idr)}</td><td>${esc(r.note)}</td></tr>`).join('')||'<tr><td colspan="3">Belum ada biaya yang dicatat.</td></tr>'}</tbody></table></div><form id="growth-spend-form" class="growth-spend-form"><label>Sumber<select name="source">${options(Object.fromEntries(Object.entries(labels).filter(([key])=>['referral','instagram','tiktok','whatsapp','website','event','other'].includes(key))))}</select></label><label>Biaya nyata (Rp)<input name="amountIdr" type="number" min="0" max="1000000000000" step="1" required></label><label>Catatan<input name="note" maxlength="500" placeholder="Contoh: iklan uji pesan Career"></label><button type="submit">Simpan biaya</button></form></section>
      <section class="growth-panel"><h2>Review mingguan & satu eksperimen utama</h2><p>Catat keputusan dari data dan percakapan. Pilih satu variabel utama untuk diuji pada minggu berikutnya. Tulis kutipan tanpa nama atau kontak pribadi.</p><form id="growth-review-form" class="growth-review-form">
        <label>Segmen yang diprioritaskan<textarea name="segmentDecision" maxlength="1000" rows="2">${esc(review.segment_decision)}</textarea></label><label>Bahasa pelanggan yang berulang<textarea name="buyerLanguage" maxlength="1500" rows="2">${esc(review.buyer_language)}</textarea></label><label>Keberatan utama<textarea name="topObjection" maxlength="1000" rows="2">${esc(review.top_objection)}</textarea></label><label>Keputusan minggu ini<textarea name="decision" maxlength="1000" rows="2">${esc(review.decision)}</textarea></label>
        <label>Variabel eksperimen<select name="experimentVariable">${options({'':'Belum ditentukan',message:'Pesan utama',cta:'CTA',sales_script:'Skrip konsultasi',price_framing:'Cara menjelaskan harga',channel:'Channel',other:'Lainnya'},review.experiment_variable)}</select></label>
        <label>Sudut pesan<select name="experimentAngle">${options({'':'Belum ditentukan',cost:'Cost',career:'Career',convenience:'Convenience',other:'Lainnya'},review.experiment_angle)}</select></label>
        <label class="growth-wide">Hipotesis yang diuji<textarea name="experimentHypothesis" maxlength="1000" rows="2">${esc(review.experiment_hypothesis)}</textarea></label><label>Ukuran keberhasilan<input name="successMetric" maxlength="300" value="${esc(review.success_metric)}" placeholder="Contoh: qualified lead dari referral"></label>
        <label>Penanggung jawab<select name="experimentOwner"><option value="${esc(review.experiment_owner||'')}">Memuat PIC…</option></select></label><label>Status<select name="status">${options({planned:'Direncanakan',running:'Berjalan',complete:'Selesai'},review.status||'planned')}</select></label>
        <label class="growth-wide">Hasil eksperimen<textarea name="experimentResult" maxlength="1000" rows="2">${esc(review.experiment_result)}</textarea></label><div class="growth-wide"><button type="submit" class="growth-primary">Simpan review</button></div>
      </form></section>`;
    controlLabels($('content'));setupSpend();setupReview();
  }
  function setupSpend(){
    const form=$('spend-form');function fill(){const r=report.spend.find(x=>x.source===form.elements.source.value);form.elements.amountIdr.value=r?.amount_idr??'';form.elements.note.value=r?.note||'';}
    form.elements.source.onchange=fill;fill();
    form.onsubmit=async e=>{e.preventDefault();if(busy)return;if(dirty){$('notice').textContent='Simpan review mingguan dulu sebelum mencatat biaya.';return;}const r=report.spend.find(x=>x.source===form.elements.source.value),body={courseId:activeCourse||null,week:activeWeek,source:form.elements.source.value,amountIdr:Number(form.elements.amountIdr.value),note:form.elements.note.value,version:r?.version||0};
      await save(()=>api('/crm/growth/spend',body,'PUT'),'Biaya tersimpan.');};
  }
  function setupReview(){
    const form=$('review-form'),expected=report.review?.version||0;
    form.addEventListener('input',()=>dirty=true);form.addEventListener('change',()=>dirty=true);
    async function people(){try{const data=await api('/assignees?'+new URLSearchParams({division:'marketing',courseId:activeCourse})),entries={'':'Belum ditugaskan',...Object.fromEntries(data.people.map(p=>[p.id,p.full_name||p.id]))};form.elements.experimentOwner.innerHTML=options(entries,report.review?.experiment_owner||'');}catch{$('notice').textContent='PIC gagal dimuat. Muat ulang sebelum menyimpan review.';form.querySelector('[type="submit"]').disabled=true;}}
    people();form.onsubmit=async e=>{e.preventDefault();if(busy)return;const data=Object.fromEntries(new FormData(form));data.courseId=activeCourse||null;data.week=activeWeek;data.version=expected;data.experimentOwner=data.experimentOwner||null;
      await save(()=>api('/crm/growth/review',data,'PUT'),'Review mingguan tersimpan.');};
  }
  async function save(fn,success){busy=true;$('notice').textContent='Menyimpan…';try{await fn();dirty=false;await load();$('notice').textContent=success;}catch(e){$('notice').textContent=message(e);}finally{busy=false;}}
  $('filter').onsubmit=e=>{e.preventDefault();if(!canLeave()){e.currentTarget.elements.courseId.value=activeCourse;e.currentTarget.elements.week.value=activeWeek;return;}activeCourse=e.currentTarget.elements.courseId.value;activeWeek=e.currentTarget.elements.week.value;load();};
  const beforeUnload=e=>{if(active&&(dirty||busy)){e.preventDefault();e.returnValue='';}};
  return {open(){active=true;node.hidden=false;window.addEventListener('beforeunload',beforeUnload);onOpen();load();},canLeave,close(){active=false;dirty=false;loading++;node.hidden=true;window.removeEventListener('beforeunload',beforeUnload);}};
}
